import type { IconSvgElement } from '@hugeicons/react'
import {
  Alert02Icon,
  AbacusIcon,
  ArrowRight01Icon,
  BalanceScaleIcon,
  BombIcon,
  BookOpen01Icon,
  BubbleChatIcon,
  Cancel01Icon,
  CardExchange01Icon,
  Cards01Icon,
  Cards02Icon,
  Chair01Icon,
  ChampionIcon,
  ChessKingIcon,
  ChessPawnIcon,
  ClipboardIcon,
  Coins01Icon,
  ConfusedIcon,
  CrownIcon,
  DiceIcon,
  DominoIcon,
  EyeClosedIcon,
  EyeIcon,
  FavouriteIcon,
  FireIcon,
  FlashIcon,
  Flag02Icon,
  GlobeIcon,
  HashIcon,
  HelpCircleIcon,
  Home01Icon,
  IncognitoIcon,
  Invoice01Icon,
  Key01Icon,
  Layers01Icon,
  LetterSpacingIcon,
  Link01Icon,
  LockIcon,
  Mail01Icon,
  MaskIcon,
  Megaphone01Icon,
  Mic01Icon,
  Moon02Icon,
  PaintBrush01Icon,
  Pen01Icon,
  PencilEdit02Icon,
  PuzzleIcon,
  QuestionIcon,
  RainbowIcon,
  RocketIcon,
  SatelliteIcon,
  Search01Icon,
  SearchAreaIcon,
  Settings01Icon,
  ShuffleIcon,
  SmartPhone01Icon,
  SparklesIcon,
  SpeechIcon,
  Stairs01Icon,
  StarIcon,
  StopWatchIcon,
  Target01Icon,
  TableTennisBatIcon,
  TextFontIcon,
  Ticket01Icon,
  UserGroupIcon,
  UserMultipleIcon,
} from '@hugeicons/core-free-icons'

/**
 * Icons for feature cards on marketing & game landing pages.
 * Keyed by the `emoji` string stored on each feature entry.
 */
const FEATURE_ICONS: Record<string, IconSvgElement> = {
  '⚡': FlashIcon,
  '📡': SatelliteIcon,
  '📱': SmartPhone01Icon,
  '📞': SmartPhone01Icon,
  '🔗': Link01Icon,
  '🎯': Target01Icon,
  '🎭': MaskIcon,
  '🔥': FireIcon,
  '📋': ClipboardIcon,
  '💬': BubbleChatIcon,
  '🎲': DiceIcon,
  '🔤': TextFontIcon,
  '👑': CrownIcon,
  '🏆': ChampionIcon,
  '⛀': Coins01Icon,
  '🚀': RocketIcon,
  '🕵️': IncognitoIcon,
  '🔢': HashIcon,
  '📣': Megaphone01Icon,
  '👀': EyeIcon,
  '🎴': Cards01Icon,
  '⭐': StarIcon,
  '🪜': Stairs01Icon,
  '🪑': Chair01Icon,
  '🧾': Invoice01Icon,
  '🧩': PuzzleIcon,
  '🧨': BombIcon,
  '🤥': ConfusedIcon,
  '🤔': QuestionIcon,
  '🚩': Flag02Icon,
  '🙈': EyeClosedIcon,
  '🗣️': SpeechIcon,
  '🔠': LetterSpacingIcon,
  '🔒': LockIcon,
  '🔑': Key01Icon,
  '🔎': SearchAreaIcon,
  '🔍': Search01Icon,
  '🔀': ShuffleIcon,
  '🔁': ShuffleIcon,
  '📖': BookOpen01Icon,
  '👨‍👩‍👧': UserGroupIcon,
  '👥': UserMultipleIcon,
  '👋': UserGroupIcon,
  '🏠': Home01Icon,
  '🏓': TableTennisBatIcon,
  '🎱': Ticket01Icon,
  '🎨': PaintBrush01Icon,
  '🎛️': Settings01Icon,
  '🌰': AbacusIcon,
  '🌒': Moon02Icon,
  '🌈': RainbowIcon,
  '🃏': Cards02Icon,
  '🀄': DominoIcon,
  '➡️': ArrowRight01Icon,
  '❓': HelpCircleIcon,
  '🤷': HelpCircleIcon,
  '✏️': PencilEdit02Icon,
  '✍️': Pen01Icon,
  '✉️': Mail01Icon,
  '💌': Mail01Icon,
  '🤍': FavouriteIcon,
  '⚠️': Alert02Icon,
  '⚖️': BalanceScaleIcon,
  '♟️': ChessPawnIcon,
  '♚': ChessKingIcon,
  '⏱️': StopWatchIcon,
  '8️⃣': CardExchange01Icon,
  '2️⃣': Layers01Icon,
  '💸': Coins01Icon,
  '🆓': Coins01Icon,
  '🚫': Cancel01Icon,
  '🎙️': Mic01Icon,
  '🗳️': ClipboardIcon,
  '🧠': SparklesIcon,
  '🧊': SparklesIcon,
  '🎂': SparklesIcon,
  '🎉': SparklesIcon,
  '🌍': GlobeIcon,
  '🇳🇬': GlobeIcon,
}

/** Icon for a landing-page feature card, or undefined if its emoji has no mapping yet. */
export function featureIcon(emoji: string): IconSvgElement | undefined {
  return FEATURE_ICONS[emoji] ?? SparklesIcon
}
