/** Built-in Most Likely To prompts — 80 questions */

export const MLT_QUESTIONS: string[] = [
  'Who is most likely to laugh at every joke?',
  'Who is most likely to show up late to everything?',
  'Who is most likely to forget someone\'s birthday?',
  'Who is most likely to start dancing first at a party?',
  'Who is most likely to cry during a movie?',
  'Who is most likely to become famous?',
  'Who is most likely to get lost on the way somewhere?',
  'Who is most likely to survive a zombie apocalypse?',
  'Who is most likely to overshare on social media?',
  'Who is most likely to become a billionaire?',
  'Who is most likely to fall asleep first at a sleepover?',
  'Who is most likely to talk their way out of trouble?',
  'Who is most likely to have the wildest stories?',
  'Who is most likely to plan the best trips?',
  'Who is most likely to accidentally start drama?',
  'Who is most likely to become a parent first?',
  'Who is most likely to never get married?',
  'Who is most likely to win a reality TV show?',
  'Who is most likely to go viral for something embarrassing?',
  'Who is most likely to keep a secret forever?',
  'Who is most likely to spill the tea immediately?',
  'Who is most likely to have a secret talent?',
  'Who is most likely to become a CEO?',
  'Who is most likely to quit their job on impulse?',
  'Who is most likely to live abroad someday?',
  'Who is most likely to adopt ten pets?',
  'Who is most likely to forget where they parked?',
  'Who is most likely to order the weirdest thing on the menu?',
  'Who is most likely to become a influencer?',
  'Who is most likely to delete social media and come back a week later?',
  'Who is most likely to send a text to the wrong person?',
  'Who is most likely to laugh at the worst possible moment?',
  'Who is most likely to have the messiest room?',
  'Who is most likely to have the cleanest room?',
  'Who is most likely to win an argument they shouldn\'t?',
  'Who is most likely to lose an argument they should win?',
  'Who is most likely to become a therapist?',
  'Who is most likely to need a therapist the most?',
  'Who is most likely to get married in Vegas?',
  'Who is most likely to stay single the longest?',
  'Who is most likely to have the most exes?',
  'Who is most likely to still be friends with all their exes?',
  'Who is most likely to ghost someone?',
  'Who is most likely to double text?',
  'Who is most likely to fall in love on the first date?',
  'Who is most likely to have a situationship forever?',
  'Who is most likely to give the best advice?',
  'Who is most likely to ignore their own advice?',
  'Who is most likely to become a morning person?',
  'Who is most likely to stay up until 4am?',
  'Who is most likely to hit snooze ten times?',
  'Who is most likely to work out at 6am?',
  'Who is most likely to eat dessert before dinner?',
  'Who is most likely to cook a full meal from scratch?',
  'Who is most likely to burn toast?',
  'Who is most likely to become a foodie?',
  'Who is most likely to get food poisoning on vacation?',
  'Who is most likely to pack way too much for a weekend trip?',
  'Who is most likely to forget their charger?',
  'Who is most likely to have their phone at 1% at all times?',
  'Who is most likely to reply to emails instantly?',
  'Who is most likely to have 500 unread messages?',
  'Who is most likely to win trivia night?',
  'Who is most likely to guess wildly and still be right?',
  'Who is most likely to cheat at board games?',
  'Who is most likely to rage quit a game?',
  'Who is most likely to become a group chat admin?',
  'Who is most likely to mute the group chat?',
  'Who is most likely to send voice notes instead of texts?',
  'Who is most likely to FaceTime without warning?',
  'Who is most likely to make everyone feel welcome?',
  'Who is most likely to be the mom of the friend group?',
  'Who is most likely to be the chaotic one?',
  'Who is most likely to have the best taste in music?',
  'Who is most likely to DJ at every party?',
  'Who is most likely to sing karaoke sober?',
  'Who is most likely to need karaoke liquid courage?',
  'Who is most likely to get a tattoo on impulse?',
  'Who is most likely to have a five-year plan for everything?',
  'Who is most likely to start a business with no plan?',
  'Who is most likely to donate to every cause?',
  'Who is most likely to accidentally like an old photo while stalking?',
  'Who is most likely to have the best comeback?',
  'Who is most likely to roast everyone and mean it lovingly?',
  'Who is most likely to win a Nobel Prize?',
  'Who is most likely to end up on the news for something random?',
]

export const MLT_QUESTION_COUNT = MLT_QUESTIONS.length

function shuffleInPlace<T>(arr: T[]): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

export function pickMltQuestions(count: number): string[] {
  if (count <= 0) return []
  return shuffleInPlace([...MLT_QUESTIONS]).slice(0, Math.min(count, MLT_QUESTIONS.length))
}
