import type { SystemTrophySpec } from './types'

/**
 * Scrabble — derived at finish from `scrabble_player_state` (the in-play accumulator on `.stats`
 * plus the row's final `score`/`rack`). See `../game-facts/scrabble.ts`.
 *
 * Ordered bronze → platinum; the thresholds are the brief's (Wave 2). Two brief rows are omitted
 * as generic duplicates of the cross-game set, not reworded here:
 *   - #13 "Winner" (win a game)              → the universal `games_won`.
 *   - #30 "Scrabble Champion" (5/15/30/50)   → the generic catalog's win-count track.
 *
 * #23 Clean Rack is scored as "finished with an empty rack", which — see the facts-builder note —
 * is reachable only by going out (playing your last tile); every other ending leaves tiles on the
 * rack. It is kept as a Gold rather than dropped, since going out is a real achievement.
 */
export const SCRABBLE: SystemTrophySpec[] = [
  // ── Bronze ──────────────────────────────────────────────────────────────────────────────
  {
    suffix: 'opening_move',
    tier: 'bronze',
    title: 'Opening Move',
    description: 'Play your first word across the centre star.',
    counter: 'scrabble_opening_move_games',
    points: 10,
    sortOrder: 10,
  },
  {
    suffix: 'double_up',
    tier: 'bronze',
    title: 'Double Up',
    description: 'Cover a double-letter square.',
    counter: 'scrabble_double_letter_games',
    points: 10,
    sortOrder: 20,
  },
  {
    suffix: 'triple_threat',
    tier: 'bronze',
    title: 'Triple Threat',
    description: 'Cover a triple-letter square.',
    counter: 'scrabble_triple_letter_games',
    points: 10,
    sortOrder: 30,
  },
  {
    suffix: 'word_double',
    tier: 'bronze',
    title: 'Word Double',
    description: 'Cover a double-word square.',
    counter: 'scrabble_double_word_games',
    points: 10,
    sortOrder: 40,
  },
  {
    suffix: 'blank_slate',
    tier: 'bronze',
    title: 'Blank Slate',
    description: 'Play a blank tile.',
    counter: 'scrabble_blank_games',
    points: 10,
    sortOrder: 50,
  },
  {
    suffix: 'swap_shop',
    tier: 'bronze',
    title: 'Swap Shop',
    description: 'Exchange tiles.',
    counter: 'scrabble_swap_games',
    points: 10,
    sortOrder: 60,
  },
  {
    suffix: 'crossworder',
    tier: 'bronze',
    title: 'Crossworder',
    description: 'Form two words with a single play.',
    counter: 'scrabble_two_word_games',
    points: 15,
    sortOrder: 70,
  },
  {
    suffix: 'half_century',
    tier: 'bronze',
    title: 'Half Century',
    description: 'Score 50 or more points in one game.',
    counter: 'scrabble_half_century_games',
    points: 15,
    sortOrder: 80,
  },

  // ── Silver ──────────────────────────────────────────────────────────────────────────────
  {
    suffix: 'bingo',
    tier: 'silver',
    title: 'Bingo',
    description: 'Play all seven tiles in one turn for the 50-point bonus.',
    counter: 'scrabble_bingo_games',
    points: 30,
    sortOrder: 90,
  },
  {
    suffix: 'triple_word',
    tier: 'silver',
    title: 'Triple Word',
    description: 'Cover a triple-word square.',
    counter: 'scrabble_triple_word_games',
    points: 25,
    sortOrder: 100,
  },
  {
    suffix: 'big_play',
    tier: 'silver',
    title: 'Big Play',
    description: 'Score 40 or more points on a single word.',
    counter: 'scrabble_big_play_games',
    points: 30,
    sortOrder: 110,
  },
  {
    suffix: 'q_without_u',
    tier: 'silver',
    title: 'Q Without U',
    description: 'Play a valid Q word with no U.',
    counter: 'scrabble_q_no_u_games',
    points: 30,
    sortOrder: 120,
  },
  {
    suffix: 'long_word',
    tier: 'silver',
    title: 'Long Word',
    description: 'Play a word of eight or more letters.',
    counter: 'scrabble_long_word_games',
    points: 30,
    sortOrder: 130,
  },
  {
    suffix: 'century',
    tier: 'silver',
    title: 'Century',
    description: 'Finish with 200 or more points.',
    counter: 'scrabble_century_games',
    points: 35,
    sortOrder: 140,
  },
  {
    suffix: 'hook',
    tier: 'silver',
    title: 'Hook',
    description: 'Extend an existing word with a single tile.',
    counter: 'scrabble_hook_games',
    points: 25,
    sortOrder: 150,
  },
  {
    suffix: 'parallel_play',
    tier: 'silver',
    title: 'Parallel Play',
    description: 'Form three or more words in one turn.',
    counter: 'scrabble_parallel_games',
    points: 35,
    sortOrder: 160,
  },
  {
    suffix: 'high_value',
    tier: 'silver',
    title: 'High Value',
    description: 'Play the Z, Q, X or J on a premium square.',
    counter: 'scrabble_high_value_games',
    points: 25,
    sortOrder: 170,
  },

  // ── Gold ────────────────────────────────────────────────────────────────────────────────
  {
    suffix: 'double_bingo',
    tier: 'gold',
    title: 'Double Bingo',
    description: 'Play two bingos in one game.',
    counter: 'scrabble_double_bingo_games',
    points: 70,
    sortOrder: 180,
  },
  {
    suffix: 'monster_play',
    tier: 'gold',
    title: 'Monster Play',
    description: 'Score 80 or more points on a single word.',
    counter: 'scrabble_monster_play_games',
    points: 70,
    sortOrder: 190,
  },
  {
    suffix: 'triple_triple',
    tier: 'gold',
    title: 'Triple-Triple',
    description: 'Cover two triple-word squares with one word.',
    counter: 'scrabble_triple_triple_games',
    points: 80,
    sortOrder: 200,
  },
  {
    suffix: 'three_hundred',
    tier: 'gold',
    title: 'Three Hundred',
    description: 'Finish with 300 or more points.',
    counter: 'scrabble_three_hundred_games',
    points: 70,
    sortOrder: 210,
  },
  {
    suffix: 'clean_rack',
    tier: 'gold',
    title: 'Clean Rack',
    description: 'Finish the game having played every tile — an empty rack at the end.',
    counter: 'scrabble_clean_rack_games',
    points: 60,
    sortOrder: 220,
  },
  {
    suffix: 'comeback',
    tier: 'gold',
    title: 'Comeback',
    description: 'Win from 60 or more points behind.',
    counter: 'scrabble_comeback_wins',
    points: 80,
    sortOrder: 230,
  },
  {
    suffix: 'full_table',
    tier: 'gold',
    title: 'Full Table',
    description: 'Win a four-player game.',
    counter: 'scrabble_full_table_wins',
    points: 60,
    sortOrder: 240,
  },
  {
    suffix: 'no_swaps',
    tier: 'gold',
    title: 'No Swaps',
    description: 'Win without exchanging tiles or passing.',
    counter: 'scrabble_no_swap_wins',
    points: 70,
    sortOrder: 250,
  },

  // ── Platinum ────────────────────────────────────────────────────────────────────────────
  {
    suffix: 'triple_bingo',
    tier: 'platinum',
    title: 'Triple Bingo',
    description: 'Play three bingos in one game.',
    counter: 'scrabble_triple_bingo_games',
    points: 150,
    sortOrder: 260,
    hidden: true,
  },
  {
    suffix: 'four_hundred',
    tier: 'platinum',
    title: 'Four Hundred',
    description: 'Finish with 400 or more points.',
    counter: 'scrabble_four_hundred_games',
    points: 150,
    sortOrder: 270,
  },
  {
    suffix: 'century_word',
    tier: 'platinum',
    title: 'Century Word',
    description: 'Score 100 or more points on a single word.',
    counter: 'scrabble_century_word_games',
    points: 150,
    sortOrder: 280,
    hidden: true,
  },
]
