/**
 * The counter vocabulary — what a trophy rule is allowed to talk about.
 *
 * THIS FILE IS THE PRODUCT SURFACE, not the trophy list. A trophy is a row in `trophies`
 * that an admin can write; a *counter* is a measurement the server emits, and only code can
 * add one. So the breadth here decides how much can be built without a deploy:
 *
 *   - "Win 25 games"            → composable today, because `games_won` exists
 *   - "Win without drawing"     → needs a `wins_no_draw` counter emitted by the card games
 *
 * The registry is exported so `/admin/trophies` can *show* the vocabulary while someone is
 * writing a rule. Without that, "admin-editable" quietly means "editable if you remember the
 * counter names", and the first typo produces a trophy that is simply never earned — with no
 * error, because an unknown counter reads as zero by design.
 *
 * Adding a counter here does NOT make it real. It has to be emitted by the award pass too.
 * `availability` records how far along each one is, so the admin UI can grey out the ones that
 * would never fire rather than offering a rule that silently can't be satisfied.
 */

export type CounterScope =
  /** Tracked per game type, and also aggregated globally. */
  | 'per-game'
  /** Only meaningful across all games. */
  | 'global'

export type CounterAvailability =
  /** Emitted for every game type today. */
  | 'universal'
  /**
   * Emitted only where the server can actually determine it. `games_won` is the live example:
   * there is no universal winner on this stack, so a "win" rule silently never fires for a
   * game whose outcome the server can't resolve. `./outcome.ts` maps the 16 game types where
   * it can — call `gameTypesWithWinners()` for the current list rather than hardcoding it, and
   * warn in the admin UI when a rule targets a game type outside it.
   */
  | 'partial'
  /** Declared for the catalog's benefit, not yet emitted anywhere. */
  | 'planned'

export type CounterDef = {
  key: string
  label: string
  description: string
  scope: CounterScope
  availability: CounterAvailability
  /**
   * How this measure reads in a sentence, with `{n}` for the threshold and `{s}` for a plural
   * "s". Exists so the admin editor can say "won at least 25 games" instead of "games won of at
   * least 25" — the whole point of the sentence is that someone can check the rule without
   * knowing the format, and that only works if it reads like English.
   */
  phrase: string
}

export type DistinctDef = {
  key: string
  label: string
  description: string
  availability: CounterAvailability
  /** See `CounterDef.phrase`. */
  phrase: string
}

/**
 * Scalar counters, addressable by `{ type: 'counter', counter: <key> }`.
 *
 * Deliberately broader than the launch catalog needs. Emitting a counter nobody uses yet costs
 * one key in a jsonb blob; discovering later that you need it costs a deploy and a backfill,
 * and the backfill is impossible because the games it would have measured are already over.
 */
export const COUNTERS: readonly CounterDef[] = [
  {
    key: 'games_played',
    label: 'Games played',
    description: 'Finished games this profile took part in as a seated player.',
    scope: 'per-game',
    availability: 'universal',
    phrase: 'finished at least {n} game{s}',
  },
  {
    key: 'games_won',
    label: 'Games won',
    description: 'Finished games this profile won outright.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s}',
  },
  {
    key: 'podium_finishes',
    label: 'Podium finishes',
    description: 'Finished in the top three of a ranked game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished in the top three at least {n} time{s}',
  },
  {
    key: 'days_played',
    label: 'Days played',
    description: 'Distinct calendar days (WAT) with at least one finished game.',
    scope: 'global',
    availability: 'universal',
    phrase: 'played on at least {n} different day{s}',
  },
  {
    key: 'longest_streak',
    label: 'Longest streak',
    description: 'Best run of consecutive days played.',
    scope: 'global',
    availability: 'universal',
    phrase: 'reached a streak of at least {n} day{s} in a row',
  },
  {
    key: 'big_room_games',
    label: 'Big-room games',
    description: 'Finished games with eight or more seated players.',
    scope: 'per-game',
    availability: 'universal',
    phrase: 'finished at least {n} game{s} with 8 or more players',
  },
  {
    key: 'late_night_games',
    label: 'Late-night games',
    description: 'Games finished between midnight and 5am, local to the room.',
    scope: 'global',
    availability: 'universal',
    phrase: 'finished at least {n} game{s} after midnight',
  },
  {
    key: 'host_games',
    label: 'Games hosted',
    description: 'Finished games this profile hosted.',
    scope: 'per-game',
    availability: 'planned',
    phrase: 'hosted at least {n} game{s}',
  },
  {
    key: 'comeback_wins',
    label: 'Comeback wins',
    description: 'Won after being last at any scored checkpoint.',
    scope: 'per-game',
    availability: 'planned',
    phrase: 'won at least {n} game{s} after being last',
  },
  {
    key: 'perfect_games',
    label: 'Perfect games',
    description: 'Finished with a flawless score by that game’s own definition.',
    scope: 'per-game',
    availability: 'planned',
    phrase: 'finished at least {n} perfect game{s}',
  },
  // ── Trivia ──────────────────────────────────────────────────────────────────────────────
  // Emitted by src/lib/trophies/game-facts/trivia.ts, derived at finish from `trivia_answers`.
  // `partial` because they only ever fire for Trivia — a rule using one against another game
  // would parse and save and then never be earned, which the admin UI warns about.
  // Note the `_games` / `_wins` suffixes: these are counted ONCE PER GAME, not per event, so
  // "hit a ten-answer run in at least 1 game" is the readable form. Lifetime totals (correct
  // answers) are the exception and carry no suffix.
  {
    key: 'trivia_correct_answers',
    label: 'Trivia — correct answers',
    description: 'Questions answered correctly, across every Trivia game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'answered at least {n} Trivia question{s} correctly',
  },
  {
    key: 'trivia_first_correct_games',
    label: 'Trivia — beat everyone to it',
    description: 'Games where you were the first player to answer a question correctly.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been first to a correct answer in at least {n} game{s}',
  },
  {
    key: 'trivia_speed_demon_games',
    label: 'Trivia — first on five',
    description: 'Games where you were first correct on five or more questions.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been first correct five times in at least {n} game{s}',
  },
  {
    key: 'trivia_clean_sweep_games',
    label: 'Trivia — first on everything',
    description: 'Games where you were first correct on every question (5+ questions).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept every question in at least {n} game{s}',
  },
  {
    key: 'trivia_buzzer_beater_games',
    label: 'Trivia — buzzer beater',
    description: 'Games with a correct answer inside the last two seconds.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'answered on the buzzer in at least {n} game{s}',
  },
  {
    key: 'trivia_lightning_games',
    label: 'Trivia — lightning',
    description: 'Games where your correct answers averaged under three seconds.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'averaged under three seconds in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_3_games',
    label: 'Trivia — three in a row',
    description: 'Games with a run of three consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a three-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_5_games',
    label: 'Trivia — five in a row',
    description: 'Games with a run of five consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a five-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_10_games',
    label: 'Trivia — ten in a row',
    description: 'Games with a run of ten consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a ten-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_20_games',
    label: 'Trivia — twenty in a row',
    description: 'Games with a run of twenty consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a twenty-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_full_marks_games',
    label: 'Trivia — full marks',
    description: 'Games of five or more questions answered perfectly.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored full marks in at least {n} game{s}',
  },
  {
    key: 'trivia_perfect_10q_games',
    label: 'Trivia — perfect ten',
    description: 'Games of ten or more questions answered perfectly.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been perfect over ten questions at least {n} time{s}',
  },
  {
    key: 'trivia_flawless_wins',
    label: 'Trivia — flawless victory',
    description: 'Wins with perfect accuracy over fifteen or more questions.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won flawlessly at least {n} time{s}',
  },
  {
    key: 'trivia_custom_set_games',
    label: 'Trivia — custom sets',
    description: 'Games played on an uploaded question set.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} custom-set game{s}',
  },
  {
    key: 'trivia_big_room_15',
    label: 'Trivia — big room',
    description: 'Games played with fifteen or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} game{s} with 15+ players',
  },
  {
    key: 'trivia_packed_house_wins',
    label: 'Trivia — packed house',
    description: 'Wins in games of twenty or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with 20+ players',
  },
  {
    key: 'trivia_comeback_wins',
    label: 'Trivia — comeback',
    description: 'Wins from outside the top three at the halfway point.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'come from behind to win at least {n} time{s}',
  },
  {
    key: 'trivia_wire_to_wire_wins',
    label: 'Trivia — wire to wire',
    description: 'Wins where you led after every single question.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'led wire-to-wire in at least {n} win{s}',
  },
  // ── Codewords — from codewords_guesses + player_roles at finish ───────────────────────────────────────────────
  {
    key: 'codewords_own_word_guesses',
    label: 'Own words found',
    description: 'Your team\u2019s own words that you personally uncovered.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'found at least {n} of your team\u2019s words',
  },
  {
    key: 'codewords_neutral_guesses',
    label: 'Neutral words hit',
    description: 'Bystander words you guessed.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit at least {n} neutral word{s}',
  },
  {
    key: 'codewords_opponent_guesses',
    label: 'Opponent words hit',
    description: 'Words you guessed that belonged to the other team.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'handed the other team at least {n} word{s}',
  },
  {
    key: 'codewords_assassin_guesses',
    label: 'Assassin hit',
    description: 'Games ended by you guessing the assassin.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit the assassin at least {n} time{s}',
  },
  {
    key: 'codewords_clean_turns',
    label: 'Clean turns',
    description: 'Turns where your team guessed only its own words.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'completed at least {n} clean turn{s}',
  },
  {
    key: 'codewords_clue2_full',
    label: 'Clue for two, all found',
    description: 'Games where a clue for two had both words found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for two in at least {n} game{s}',
  },
  {
    key: 'codewords_clue3_full',
    label: 'Clue for three, all found',
    description: 'Games where a clue for three had all three found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for three in at least {n} game{s}',
  },
  {
    key: 'codewords_clue4_full',
    label: 'Clue for four, all found',
    description: 'Games where a clue for four had all four found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for four in at least {n} game{s}',
  },
  {
    key: 'codewords_clue5_full',
    label: 'Clue for five, all found',
    description: 'Games where a clue for five had all five found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for five in at least {n} game{s}',
  },
  {
    key: 'codewords_run4_guesses',
    label: 'Four on one clue',
    description: 'Games where you personally found four words on a single clue.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'found four on one clue in at least {n} game{s}',
  },
  {
    key: 'codewords_run5_guesses',
    label: 'Five on one clue',
    description: 'Games where you personally found five words on a single clue.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'found five on one clue in at least {n} game{s}',
  },
  {
    key: 'codewords_spymaster_wins',
    label: 'Wins as spymaster',
    description: 'Wins where you finished the game as spymaster.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as spymaster',
  },
  {
    key: 'codewords_operative_wins',
    label: 'Wins as operative',
    description: 'Wins where you finished the game as operative.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as operative',
  },
  {
    key: 'codewords_assassin_dodged_wins',
    label: 'Assassin dodged',
    description: 'Wins where the assassin was never turned over.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s} with the assassin untouched',
  },
  {
    key: 'codewords_perfect_wins',
    label: 'Perfect game',
    description: 'Wins where your team never guessed a wrong word.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} without a wrong guess',
  },
  {
    key: 'codewords_sweep_wins',
    label: 'Sweep',
    description: 'Wins in four clue runs or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept a win in at least {n} game{s}',
  },
  {
    key: 'codewords_flawless_sweep_wins',
    label: 'Flawless sweep',
    description: 'Wins in three runs with no wrong guesses.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'managed a flawless sweep at least {n} time{s}',
  },
  {
    key: 'codewords_clutch_wins',
    label: 'Clutch',
    description: 'Wins with the opponent one word from taking it.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won from the brink at least {n} time{s}',
  },
  {
    key: 'codewords_comeback_wins',
    label: 'Comeback',
    description: 'Wins from three or more words behind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'come from behind to win at least {n} time{s}',
  },
  // ── Chess — from replaying chess_sessions.pgn at finish ───────────────────────────────────────────────
  {
    key: 'chess_captures',
    label: 'Pieces captured',
    description: 'Enemy pieces you have taken.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} piece{s}',
  },
  {
    key: 'chess_checks_given',
    label: 'Checks given',
    description: 'Moves of yours that put the enemy king in check.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'given check at least {n} time{s}',
  },
  {
    key: 'chess_castles',
    label: 'Castled',
    description: 'Times you have castled.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'castled at least {n} time{s}',
  },
  {
    key: 'chess_queenside_castles',
    label: 'Castled queenside',
    description: 'Times you have castled long.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'castled queenside at least {n} time{s}',
  },
  {
    key: 'chess_promotions',
    label: 'Pawns promoted',
    description: 'Pawns you have promoted.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'promoted at least {n} pawn{s}',
  },
  {
    key: 'chess_underpromotions',
    label: 'Underpromotions',
    description: 'Pawns promoted to something other than a queen.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'underpromoted at least {n} time{s}',
  },
  {
    key: 'chess_queens_captured',
    label: 'Queens captured',
    description: 'Enemy queens you have taken.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} queen{s}',
  },
  {
    key: 'chess_en_passant',
    label: 'En passant',
    description: 'En passant captures you have made.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured en passant at least {n} time{s}',
  },
  {
    key: 'chess_forks',
    label: 'Forks',
    description: 'Checks that also attacked another piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'forked your opponent at least {n} time{s}',
  },
  {
    key: 'chess_double_checks',
    label: 'Double checks',
    description: 'Positions where two of your pieces checked at once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'delivered at least {n} double check{s}',
  },
  {
    key: 'chess_endgame_reached',
    label: 'Endgame reached',
    description: 'Games that reached six pieces or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached an endgame in at least {n} game{s}',
  },
  {
    key: 'chess_two_queens_games',
    label: 'Two queens',
    description: 'Games where you had two queens on the board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'had two queens in at least {n} game{s}',
  },
  {
    key: 'chess_wins_checkmate',
    label: 'Wins by checkmate',
    description: 'Games won by delivering mate.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won by checkmate at least {n} time{s}',
  },
  {
    key: 'chess_wins_timeout',
    label: 'Wins on time',
    description: 'Games won by the opponent running out of clock.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won on time at least {n} time{s}',
  },
  {
    key: 'chess_wins_resignation',
    label: 'Wins by resignation',
    description: 'Games the opponent resigned or abandoned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won by resignation at least {n} time{s}',
  },
  {
    key: 'chess_wins_under_10s',
    label: 'Wins under pressure',
    description: 'Timed wins with under ten seconds left on your own clock.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won with under ten seconds left at least {n} time{s}',
  },
  {
    key: 'chess_wins_blitz',
    label: 'Blitz wins',
    description: 'Wins in a three-minute game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} blitz game{s}',
  },
  {
    key: 'chess_wins_after_queen_loss',
    label: 'Wins without your queen',
    description: 'Wins in games where your queen was captured.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} after losing your queen',
  },
  {
    key: 'chess_wins_material_down_move20',
    label: 'Wins from behind',
    description: 'Wins while behind on material at move twenty.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won from material down at least {n} time{s}',
  },
  {
    key: 'chess_wins_clean_sheet',
    label: 'Clean sheet',
    description: 'Wins without losing a single piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without losing a piece at least {n} time{s}',
  },
  {
    key: 'chess_wins_back_rank',
    label: 'Back-rank mates',
    description: 'Wins by mating on the back rank.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'delivered at least {n} back-rank mate{s}',
  },
  {
    key: 'chess_wins_knight_mate',
    label: 'Knight mates',
    description: 'Wins where a knight delivered mate.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'mated with a knight at least {n} time{s}',
  },
  {
    key: 'chess_wins_mate_in_20',
    label: 'Quick mates',
    description: 'Wins by checkmate in twenty moves or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'mated inside twenty moves at least {n} time{s}',
  },
  {
    key: 'chess_wins_mate_in_12',
    label: 'Miniatures',
    description: 'Wins by checkmate in twelve moves or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'mated inside twelve moves at least {n} time{s}',
  },
  {
    key: 'chess_wins_60_moves',
    label: 'Long games',
    description: 'Wins in games lasting sixty moves or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a sixty-move game at least {n} time{s}',
  },
  {
    key: 'chess_draws_stalemate',
    label: 'Stalemates',
    description: 'Games that ended in stalemate.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached stalemate at least {n} time{s}',
  },
  // ── Yahtzee — from the persisted 13-cell scorecard ───────────────────────────────────────────────
  {
    key: 'yahtzee_full_house_scored',
    label: 'Full house',
    description: 'Games where you scored a full house.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a full house in at least {n} game{s}',
  },
  {
    key: 'yahtzee_small_straight_scored',
    label: 'Small straight',
    description: 'Games where you scored a small straight.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a small straight in at least {n} game{s}',
  },
  {
    key: 'yahtzee_large_straight_scored',
    label: 'Large straight',
    description: 'Games where you scored a large straight.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a large straight in at least {n} game{s}',
  },
  {
    key: 'yahtzee_three_kind_scored',
    label: 'Three of a kind',
    description: 'Games where you scored three of a kind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored three of a kind in at least {n} game{s}',
  },
  {
    key: 'yahtzee_four_kind_scored',
    label: 'Four of a kind',
    description: 'Games where you scored four of a kind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored four of a kind in at least {n} game{s}',
  },
  {
    key: 'yahtzee_chance_25_plus',
    label: 'Chance 25+',
    description: 'Games where Chance scored twenty-five or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 25+ in Chance in at least {n} game{s}',
  },
  {
    key: 'yahtzee_chance_perfect_30',
    label: 'Perfect chance',
    description: 'Games where Chance scored the maximum thirty.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'maxed Chance in at least {n} game{s}',
  },
  {
    key: 'yahtzee_scored_yahtzee',
    label: 'Yahtzee scored',
    description: 'Games where you took a Yahtzee for fifty.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a Yahtzee in at least {n} game{s}',
  },
  {
    key: 'yahtzee_upper_bonus_games',
    label: 'Upper bonus',
    description: 'Games where you earned the thirty-five point upper bonus.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'earned the upper bonus in at least {n} game{s}',
  },
  {
    key: 'yahtzee_upper_70_plus',
    label: 'Upper cut',
    description: 'Games with seventy or more in the upper section.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 70+ upstairs in at least {n} game{s}',
  },
  {
    key: 'yahtzee_sixes_24_plus',
    label: 'Sixes full',
    description: 'Games where Sixes scored twenty-four or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 24+ in Sixes in at least {n} game{s}',
  },
  {
    key: 'yahtzee_four_kind_27_plus',
    label: 'Heavy hitter',
    description: 'Games where Four of a Kind scored twenty-seven or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 27+ in four of a kind in at least {n} game{s}',
  },
  {
    key: 'yahtzee_both_straights_games',
    label: 'Both straights',
    description: 'Games where you scored both straights.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored both straights in at least {n} game{s}',
  },
  {
    key: 'yahtzee_no_zero_games',
    label: 'No zeros',
    description: 'Games where every category scored above zero.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'filled a card with no zeros at least {n} time{s}',
  },
  {
    key: 'yahtzee_lower_sweep_games',
    label: 'Full sweep',
    description: 'Games where every lower category scored above zero.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept the lower section at least {n} time{s}',
  },
  {
    key: 'yahtzee_flawless_card_games',
    label: 'Flawless card',
    description: 'Games with the upper bonus and no zeros anywhere.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'filled a flawless card at least {n} time{s}',
  },
  {
    key: 'yahtzee_games_200_plus',
    label: 'Century',
    description: 'Games finishing on two hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 200+ at least {n} time{s}',
  },
  {
    key: 'yahtzee_games_250_plus',
    label: 'High roller',
    description: 'Games finishing on two hundred and fifty or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 250+ at least {n} time{s}',
  },
  {
    key: 'yahtzee_games_300_plus',
    label: 'Three hundred club',
    description: 'Games finishing on three hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 300+ at least {n} time{s}',
  },
  {
    key: 'yahtzee_multiplayer_wins',
    label: 'Wins',
    description: 'Multiplayer games won.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s}',
  },
  {
    key: 'yahtzee_big_table_wins',
    label: 'Table beater',
    description: 'Wins with four or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with 4+ players',
  },
  {
    key: 'chess_wins_smothered',
    label: 'Chess — smothered mate',
    description: 'Wins by smothered mate: a knight mates a king walled in by its own pieces.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'delivered at least {n} smothered mate{s}',
  },
  {
    key: 'chess_wins_queen_sac',
    label: 'Chess — won without your queen',
    description: 'Wins where your queen was captured and the opponent kept theirs.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} a queen down',
  },
  {
    key: 'yahtzee_bonus_earned',
    label: 'Yahtzee — bonus earned',
    description: 'Games where you earned at least one 100-point Yahtzee bonus.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'earned a Yahtzee bonus in at least {n} game{s}',
  },
  {
    key: 'yahtzee_joker_used',
    label: 'Yahtzee — Joker scored',
    description: 'Games where you scored a Yahtzee under the Joker rule.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'used the Joker rule in at least {n} game{s}',
  },
  // ── Crazy Eights — from crazy_eights_player_hands.stats at finish ───────────────────────────────────────────
  {
    key: 'c8_eights_played',
    label: 'Crazy Eights — 8s played',
    description: '8s played across Crazy Eights games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Crazy Eight{s}',
  },
  {
    key: 'c8_pick_twos_played',
    label: 'Crazy Eights — Pick Twos',
    description: '2s played as a Pick Two.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Pick Two{s}',
  },
  {
    key: 'c8_pick_twos_stacked',
    label: 'Crazy Eights — Pick Twos stacked',
    description: '2s stacked onto an active Pick Two.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'stacked at least {n} Pick Two{s}',
  },
  {
    key: 'c8_skips_played',
    label: 'Crazy Eights — Skips',
    description: 'Jacks or Aces played as a Skip.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Skip{s}',
  },
  {
    key: 'c8_reverses_played',
    label: 'Crazy Eights — Reverses',
    description: 'Queens played as a Reverse.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Reverse{s}',
  },
  {
    key: 'c8_jokers_played',
    label: 'Crazy Eights — Jokers',
    description: 'Jokers played.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Joker{s}',
  },
  {
    key: 'c8_cards_drawn',
    label: 'Crazy Eights — cards drawn',
    description: 'Cards drawn from the pile.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'drew at least {n} card{s}',
  },
  {
    key: 'c8_suit_changes_3_games',
    label: 'Crazy Eights — suit changer',
    description: 'Games where you changed the suit three times.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'changed the suit three times in at least {n} game{s}',
  },
  {
    key: 'c8_drew_5_games',
    label: 'Crazy Eights — deck diver',
    description: 'Games where you drew five cards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'drew five cards in at least {n} game{s}',
  },
  {
    key: 'c8_three_eights_games',
    label: 'Crazy Eights — eight ball',
    description: 'Games where you played three 8s.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three 8s in at least {n} game{s}',
  },
  {
    key: 'c8_suit_run_4_games',
    label: 'Crazy Eights — suit run',
    description: 'Games with four same-suit cards in a row.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played four same-suit cards in a row in at least {n} game{s}',
  },
  {
    key: 'c8_rank_run_3_games',
    label: 'Crazy Eights — rank run',
    description: 'Games with three same-rank cards in a row.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three same-rank cards in a row in at least {n} game{s}',
  },
  {
    key: 'c8_all_suits_games',
    label: 'Crazy Eights — full deck',
    description: 'Games where you played every suit.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played every suit in at least {n} game{s}',
  },
  {
    key: 'c8_three_skips_games',
    label: 'Crazy Eights — skip to the end',
    description: 'Games where you played three Skips.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three Skips in at least {n} game{s}',
  },
  {
    key: 'c8_two_queens_games',
    label: 'Crazy Eights — round trip',
    description: 'Games where you played two Queens.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played two Queens in at least {n} game{s}',
  },
  {
    key: 'c8_no_pick_two_games',
    label: 'Crazy Eights — untouched',
    description: 'Games finished without taking a Pick Two.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished at least {n} game{s} without taking a Pick Two',
  },
  {
    key: 'c8_quickfire_wins',
    label: 'Crazy Eights — quickfire',
    description: 'Wins in eight turns or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} in eight turns or fewer',
  },
  {
    key: 'c8_survivor_wins',
    label: 'Crazy Eights — survivor',
    description: 'Wins after drawing ten or more cards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} after drawing ten or more cards',
  },
  {
    key: 'c8_comeback_wins',
    label: 'Crazy Eights — comeback',
    description: 'Wins after holding twelve or more cards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} after holding twelve or more cards',
  },
  {
    key: 'c8_full_table_wins',
    label: 'Crazy Eights — full table',
    description: 'Wins in a six-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} six-player game{s}',
  },
  {
    key: 'c8_suit_master_wins',
    label: 'Crazy Eights — suit master',
    description: 'Wins having played every suit and an 8.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} having played every suit and an 8',
  },
  {
    key: 'c8_suit_sweep_wins',
    label: 'Crazy Eights — suit sweep',
    description: 'Wins having played every suit, an 8 and a Joker.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} having played every suit, an 8 and a Joker',
  },
  {
    key: 'c8_flawless_wins',
    label: 'Crazy Eights — flawless',
    description: 'Wins without drawing a card.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} without drawing a card',
  },
  {
    key: 'c8_eight_finish_wins',
    label: 'Crazy Eights — eight finish',
    description: 'Wins on an 8.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on an 8',
  },
  {
    key: 'c8_joker_finish_wins',
    label: 'Crazy Eights — joker finish',
    description: 'Wins on a Joker.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on a Joker',
  },
  // ── Ludo — from ludo_player_state.game_counters at finish ───────────────────────────────────────────
  {
    key: 'ludo_sixes_rolled',
    label: 'Ludo — sixes rolled',
    description: 'Sixes rolled across Ludo games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled at least {n} six{es}',
  },
  {
    key: 'ludo_double_sixes',
    label: 'Ludo — double sixes',
    description: 'Double sixes rolled.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled at least {n} double six{es}',
  },
  {
    key: 'ludo_captures_made',
    label: 'Ludo — captures',
    description: 'Opponent pieces captured.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} piece{s}',
  },
  {
    key: 'ludo_safe_landings',
    label: 'Ludo — safe landings',
    description: 'Landings on a safe square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed on a safe square at least {n} time{s}',
  },
  {
    key: 'ludo_pieces_deployed',
    label: 'Ludo — pieces deployed',
    description: 'Pieces brought out of the yard.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'brought out at least {n} piece{s}',
  },
  {
    key: 'ludo_times_captured',
    label: 'Ludo — pieces lost',
    description: 'Your pieces captured by opponents.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'lost at least {n} piece{s} to capture',
  },
  {
    key: 'ludo_six_sense_games',
    label: 'Ludo — three sixes',
    description: 'Games where you rolled three sixes.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled three sixes in at least {n} game{s}',
  },
  {
    key: 'ludo_dice_hot_games',
    label: 'Ludo — five sixes',
    description: 'Games where you rolled five sixes.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled five sixes in at least {n} game{s}',
  },
  {
    key: 'ludo_full_deploy_games',
    label: 'Ludo — full deployment',
    description: 'Games with all four pieces out at once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'had all four pieces out in at least {n} game{s}',
  },
  {
    key: 'ludo_shield_games',
    label: 'Ludo — shield',
    description: 'Games where you formed a two-piece shield.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'formed a two-piece shield in at least {n} game{s}',
  },
  {
    key: 'ludo_double_capture_games',
    label: 'Ludo — double capture',
    description: 'Games where you captured two with one move.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured two with one move in at least {n} game{s}',
  },
  {
    key: 'ludo_sent_packing_games',
    label: 'Ludo — sent packing',
    description: 'Games where you captured one opponent three times.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured one opponent three times in at least {n} game{s}',
  },
  {
    key: 'ludo_escape_artist_games',
    label: 'Ludo — escape artist',
    description: 'Games where a captured piece still got home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'brought a captured piece home in at least {n} game{s}',
  },
  {
    key: 'ludo_fast_start_games',
    label: 'Ludo — fast start',
    description: 'Games where you deployed on the first roll.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'deployed on the first roll in at least {n} game{s}',
  },
  {
    key: 'ludo_gridlock_games',
    label: 'Ludo — gridlock',
    description: 'Games where you forfeited on three double sixes.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'forfeited on three double sixes in at least {n} game{s}',
  },
  {
    key: 'ludo_pieces_home_1',
    label: 'Ludo — one home',
    description: 'Games where you got a piece home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got a piece home in at least {n} game{s}',
  },
  {
    key: 'ludo_pieces_home_2',
    label: 'Ludo — two home',
    description: 'Games where you got two pieces home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got two pieces home in at least {n} game{s}',
  },
  {
    key: 'ludo_pieces_home_3',
    label: 'Ludo — three home',
    description: 'Games where you got three pieces home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got three pieces home in at least {n} game{s}',
  },
  {
    key: 'ludo_clean_sweep_games',
    label: 'Ludo — clean sweep',
    description: 'Games where you captured five pieces.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured five in a game at least {n} time{s}',
  },
  {
    key: 'ludo_untouched_wins',
    label: 'Ludo — untouchable',
    description: 'Wins without losing a piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without losing a piece at least {n} time{s}',
  },
  {
    key: 'ludo_comeback_wins',
    label: 'Ludo — comeback',
    description: 'Wins after a full yard-out.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won after a full yard-out at least {n} time{s}',
  },
  {
    key: 'ludo_runaway_games',
    label: 'Ludo — runaway',
    description: 'Wins before a rival got two pieces home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won before a rival got two home at least {n} time{s}',
  },
  {
    key: 'ludo_four_corners_wins',
    label: 'Ludo — four corners',
    description: 'Wins in a four-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a four-player game at least {n} time{s}',
  },
  {
    key: 'ludo_perfect_run_wins',
    label: 'Ludo — perfect run',
    description: 'Untouched wins in a four-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a four-player game untouched at least {n} time{s}',
  },
  {
    key: 'ludo_untouched_sweep_wins',
    label: 'Ludo — untouched sweep',
    description: 'Wins with five or more captures and none lost.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won with 5+ captures and none lost at least {n} time{s}',
  },
  // ── Monopoly — from the finished board + player_state ───────────────────────────────────────────
  {
    key: 'monopoly_passed_go',
    label: 'Monopoly — passed GO',
    description: 'Games where you passed GO at least once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'passed GO in at least {n} game{s}',
  },
  {
    key: 'monopoly_three_properties',
    label: 'Monopoly — three properties',
    description: 'Games ending with three or more properties owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned three or more properties in at least {n} game{s}',
  },
  {
    key: 'monopoly_ten_properties',
    label: 'Monopoly — ten properties',
    description: 'Games ending with ten or more properties owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned ten or more properties in at least {n} game{s}',
  },
  {
    key: 'monopoly_full_color_set',
    label: 'Monopoly — colour set',
    description: 'Games where you owned a full colour group.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'completed a colour set in at least {n} game{s}',
  },
  {
    key: 'monopoly_both_utilities',
    label: 'Monopoly — both utilities',
    description: 'Games ending with both utilities owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned both utilities in at least {n} game{s}',
  },
  {
    key: 'monopoly_two_stations',
    label: 'Monopoly — two stations',
    description: 'Games ending with two or more stations owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned two or more stations in at least {n} game{s}',
  },
  {
    key: 'monopoly_all_stations',
    label: 'Monopoly — all stations',
    description: 'Games ending with all four stations owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned all four stations in at least {n} game{s}',
  },
  {
    key: 'monopoly_blue_chip',
    label: 'Monopoly — blue chip',
    description: 'Games where you owned both the dark blue and green monopolies.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'held the blue-chip monopolies in at least {n} game{s}',
  },
  {
    key: 'monopoly_one_side',
    label: 'Monopoly — whole side',
    description: 'Games where you owned every property on one side of the board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned a whole side in at least {n} game{s}',
  },
  {
    key: 'monopoly_three_houses',
    label: 'Monopoly — three houses',
    description: 'Games where you built three houses on a single property.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'built three houses in at least {n} game{s}',
  },
  {
    key: 'monopoly_naija_wins',
    label: 'Monopoly — Naija win',
    description: 'Wins on the Naija board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on the Naija board',
  },
  {
    key: 'monopoly_london_wins',
    label: 'Monopoly — London win',
    description: 'Wins on the classic London board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on the London board',
  },
  {
    key: 'monopoly_last_one_standing',
    label: 'Monopoly — last one standing',
    description: 'Wins of three or more players by bankrupting everyone else.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been last one standing in at least {n} game{s}',
  },
  // ── Text Charades ───────────────────────────────────────────────
  {
    key: 'describe_it_all_rounder_games',
    label: 'Text Charades — all rounder games',
    description: 'Text Charades: all rounder games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'describe_it_big_room_12',
    label: 'Text Charades — big room 12',
    description: 'Text Charades: big room 12.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_big_team_games',
    label: 'Text Charades — big team games',
    description: 'Text Charades: big team games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'describe_it_clean_sweep_wins',
    label: 'Text Charades — clean sweep wins',
    description: 'Text Charades: clean sweep wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'describe_it_comeback_wins',
    label: 'Text Charades — comeback wins',
    description: 'Text Charades: comeback wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'describe_it_custom_set_games',
    label: 'Text Charades — custom set games',
    description: 'Text Charades: custom set games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'describe_it_describer_10_round',
    label: 'Text Charades — describer 10 round',
    description: 'Text Charades: describer 10 round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_describer_12_round',
    label: 'Text Charades — describer 12 round',
    description: 'Text Charades: describer 12 round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_describer_5_round',
    label: 'Text Charades — describer 5 round',
    description: 'Text Charades: describer 5 round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_describer_8_round',
    label: 'Text Charades — describer 8 round',
    description: 'Text Charades: describer 8 round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_describer_turns',
    label: 'Text Charades — describer turns',
    description: 'Text Charades: describer turns.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_flawless_wins',
    label: 'Text Charades — flawless wins',
    description: 'Text Charades: flawless wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'describe_it_guess_run_3',
    label: 'Text Charades — guess run 3',
    description: 'Text Charades: guess run 3.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_guess_run_5',
    label: 'Text Charades — guess run 5',
    description: 'Text Charades: guess run 5.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_packed_house_wins',
    label: 'Text Charades — packed house wins',
    description: 'Text Charades: packed house wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'describe_it_perfect_round_games',
    label: 'Text Charades — perfect round games',
    description: 'Text Charades: perfect round games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'describe_it_round_guess_3',
    label: 'Text Charades — round guess 3',
    description: 'Text Charades: round guess 3.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_words_guessed',
    label: 'Text Charades — words guessed',
    description: 'Text Charades: words guessed.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'describe_it_wordsmith_games',
    label: 'Text Charades — wordsmith games',
    description: 'Text Charades: wordsmith games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  // ── Mafia ───────────────────────────────────────────────
  {
    key: 'mafia_arsonist_wins',
    label: 'Mafia — arsonist wins',
    description: 'Mafia: arsonist wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mafia_big_game_12',
    label: 'Mafia — big game 12',
    description: 'Mafia: big game 12.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mafia_bodyguard_hits',
    label: 'Mafia — bodyguard hits',
    description: 'Mafia: bodyguard hits.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mafia_clean_sweep_wins',
    label: 'Mafia — clean sweep wins',
    description: 'Mafia: clean sweep wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mafia_full_house_16',
    label: 'Mafia — full house 16',
    description: 'Mafia: full house 16.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mafia_jester_wins',
    label: 'Mafia — jester wins',
    description: 'Mafia: jester wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mafia_last_villager',
    label: 'Mafia — last villager',
    description: 'Mafia: last villager.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mafia_lovers_wins',
    label: 'Mafia — lovers wins',
    description: 'Mafia: lovers wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mafia_lynched_games',
    label: 'Mafia — lynched games',
    description: 'Mafia: lynched games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'mafia_mafia_games',
    label: 'Mafia — mafia games',
    description: 'Mafia: mafia games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'mafia_mafia_wins',
    label: 'Mafia — mafia wins',
    description: 'Mafia: mafia wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mafia_serial_killer_wins',
    label: 'Mafia — serial killer wins',
    description: 'Mafia: serial killer wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mafia_survivor_games',
    label: 'Mafia — survivor games',
    description: 'Mafia: survivor games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'mafia_village_wins',
    label: 'Mafia — village wins',
    description: 'Mafia: village wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  // ── Scrabble ───────────────────────────────────────────────
  {
    key: 'scrabble_big_play_games',
    label: 'Scrabble — big play games',
    description: 'Scrabble: big play games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_bingo_games',
    label: 'Scrabble — bingo games',
    description: 'Scrabble: bingo games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_blank_games',
    label: 'Scrabble — blank games',
    description: 'Scrabble: blank games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_century_games',
    label: 'Scrabble — century games',
    description: 'Scrabble: century games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_century_word_games',
    label: 'Scrabble — century word games',
    description: 'Scrabble: century word games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_clean_rack_games',
    label: 'Scrabble — clean rack games',
    description: 'Scrabble: clean rack games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_comeback_wins',
    label: 'Scrabble — comeback wins',
    description: 'Scrabble: comeback wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'scrabble_double_bingo_games',
    label: 'Scrabble — double bingo games',
    description: 'Scrabble: double bingo games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_double_letter_games',
    label: 'Scrabble — double letter games',
    description: 'Scrabble: double letter games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_double_word_games',
    label: 'Scrabble — double word games',
    description: 'Scrabble: double word games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_four_hundred_games',
    label: 'Scrabble — four hundred games',
    description: 'Scrabble: four hundred games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_full_table_wins',
    label: 'Scrabble — full table wins',
    description: 'Scrabble: full table wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'scrabble_half_century_games',
    label: 'Scrabble — half century games',
    description: 'Scrabble: half century games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_high_value_games',
    label: 'Scrabble — high value games',
    description: 'Scrabble: high value games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_hook_games',
    label: 'Scrabble — hook games',
    description: 'Scrabble: hook games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_long_word_games',
    label: 'Scrabble — long word games',
    description: 'Scrabble: long word games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_monster_play_games',
    label: 'Scrabble — monster play games',
    description: 'Scrabble: monster play games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_no_swap_wins',
    label: 'Scrabble — no swap wins',
    description: 'Scrabble: no swap wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'scrabble_opening_move_games',
    label: 'Scrabble — opening move games',
    description: 'Scrabble: opening move games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_parallel_games',
    label: 'Scrabble — parallel games',
    description: 'Scrabble: parallel games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_q_no_u_games',
    label: 'Scrabble — q no u games',
    description: 'Scrabble: q no u games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_swap_games',
    label: 'Scrabble — swap games',
    description: 'Scrabble: swap games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_three_hundred_games',
    label: 'Scrabble — three hundred games',
    description: 'Scrabble: three hundred games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_bingo_games',
    label: 'Scrabble — triple bingo games',
    description: 'Scrabble: triple bingo games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_letter_games',
    label: 'Scrabble — triple letter games',
    description: 'Scrabble: triple letter games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_triple_games',
    label: 'Scrabble — triple triple games',
    description: 'Scrabble: triple triple games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_word_games',
    label: 'Scrabble — triple word games',
    description: 'Scrabble: triple word games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'scrabble_two_word_games',
    label: 'Scrabble — two word games',
    description: 'Scrabble: two word games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  // ── Checkers ───────────────────────────────────────────────
  {
    key: 'checkers_back_row_games',
    label: 'Checkers — back row games',
    description: 'Checkers: back row games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_blitz_wins',
    label: 'Checkers — blitz wins',
    description: 'Checkers: blitz wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_blockade_wins',
    label: 'Checkers — blockade wins',
    description: 'Checkers: blockade wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_captures',
    label: 'Checkers — captures',
    description: 'Checkers: captures.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'checkers_clock_watcher_wins',
    label: 'Checkers — clock watcher wins',
    description: 'Checkers: clock watcher wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_comeback_wins',
    label: 'Checkers — comeback wins',
    description: 'Checkers: comeback wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_double_jump_games',
    label: 'Checkers — double jump games',
    description: 'Checkers: double jump games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_draw_games',
    label: 'Checkers — draw games',
    description: 'Checkers: draw games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_endgame_master_wins',
    label: 'Checkers — endgame master wins',
    description: 'Checkers: endgame master wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_enemy_kings_captured',
    label: 'Checkers — enemy kings captured',
    description: 'Checkers: enemy kings captured.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'checkers_five_down_games',
    label: 'Checkers — five down games',
    description: 'Checkers: five down games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_flying_king_games',
    label: 'Checkers — flying king games',
    description: 'Checkers: flying king games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_king_me_twice_games',
    label: 'Checkers — king me twice games',
    description: 'Checkers: king me twice games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_kings_court_games',
    label: 'Checkers — kings court games',
    description: 'Checkers: kings court games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_kings_made',
    label: 'Checkers — kings made',
    description: 'Checkers: kings made.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'checkers_majority_rule_games',
    label: 'Checkers — majority rule games',
    description: 'Checkers: majority rule games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_quad_jump_games',
    label: 'Checkers — quad jump games',
    description: 'Checkers: quad jump games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_quick_win_wins',
    label: 'Checkers — quick win wins',
    description: 'Checkers: quick win wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_seed_master_games',
    label: 'Checkers — seed master games',
    description: 'Checkers: seed master games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_street_rules_wins',
    label: 'Checkers — street rules wins',
    description: 'Checkers: street rules wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_total_victory_wins',
    label: 'Checkers — total victory wins',
    description: 'Checkers: total victory wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'checkers_trade_games',
    label: 'Checkers — trade games',
    description: 'Checkers: trade games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_triple_jump_games',
    label: 'Checkers — triple jump games',
    description: 'Checkers: triple jump games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'did it in at least {n} game{s}',
  },
  {
    key: 'checkers_untouched_wins',
    label: 'Checkers — untouched wins',
    description: 'Checkers: untouched wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  // ── Mahjong ───────────────────────────────────────────────
  {
    key: 'mahjong_added_kongs',
    label: 'Mahjong — added kongs',
    description: 'Mahjong: added kongs.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_all_seats',
    label: 'Mahjong — all seats',
    description: 'Mahjong: all seats.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_chows_called',
    label: 'Mahjong — chows called',
    description: 'Mahjong: chows called.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_concealed_kongs',
    label: 'Mahjong — concealed kongs',
    description: 'Mahjong: concealed kongs.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_concealed_wins',
    label: 'Mahjong — concealed wins',
    description: 'Mahjong: concealed wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mahjong_discards',
    label: 'Mahjong — discards',
    description: 'Mahjong: discards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_double_kong',
    label: 'Mahjong — double kong',
    description: 'Mahjong: double kong.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_exhaustive_draws_seen',
    label: 'Mahjong — exhaustive draws seen',
    description: 'Mahjong: exhaustive draws seen.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_four_melds',
    label: 'Mahjong — four melds',
    description: 'Mahjong: four melds.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_grand_slam',
    label: 'Mahjong — grand slam',
    description: 'Mahjong: grand slam.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_hands_as_east',
    label: 'Mahjong — hands as east',
    description: 'Mahjong: hands as east.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_hands_won',
    label: 'Mahjong — hands won',
    description: 'Mahjong: hands won.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_heavenly_hand',
    label: 'Mahjong — heavenly hand',
    description: 'Mahjong: heavenly hand.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_high_fan',
    label: 'Mahjong — high fan',
    description: 'Mahjong: high fan.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_kongs_called',
    label: 'Mahjong — kongs called',
    description: 'Mahjong: kongs called.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_no_call_wins',
    label: 'Mahjong — no call wins',
    description: 'Mahjong: no call wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mahjong_pungs_called',
    label: 'Mahjong — pungs called',
    description: 'Mahjong: pungs called.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_quick_hand',
    label: 'Mahjong — quick hand',
    description: 'Mahjong: quick hand.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_self_draw_wins',
    label: 'Mahjong — self draw wins',
    description: 'Mahjong: self draw wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mahjong_seven_pairs_wins',
    label: 'Mahjong — seven pairs wins',
    description: 'Mahjong: seven pairs wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mahjong_table_sweep',
    label: 'Mahjong — table sweep',
    description: 'Mahjong: table sweep.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_thirteen_orphans_wins',
    label: 'Mahjong — thirteen orphans wins',
    description: 'Mahjong: thirteen orphans wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s}',
  },
  {
    key: 'mahjong_triple_meld',
    label: 'Mahjong — triple meld',
    description: 'Mahjong: triple meld.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_won_fate_round',
    label: 'Mahjong — won fate round',
    description: 'Mahjong: won fate round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_won_hong_kong',
    label: 'Mahjong — won hong kong',
    description: 'Mahjong: won hong kong.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_won_mcr',
    label: 'Mahjong — won mcr',
    description: 'Mahjong: won mcr.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
  {
    key: 'mahjong_won_riichi',
    label: 'Mahjong — won riichi',
    description: 'Mahjong: won riichi.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached at least {n}',
  },
] as const

/**
 * Set-valued measures, addressable by `{ type: 'distinct', key: <key> }`. Backed by
 * `player_distinct`, where the primary key does the deduping and `count(*)` is the value.
 */
export const DISTINCT_SETS: readonly DistinctDef[] = [
  {
    key: 'modes_played',
    label: 'Game modes played',
    description: 'How many different game types this profile has finished.',
    availability: 'universal',
    phrase: 'played at least {n} different game mode{s}',
  },
  {
    key: 'opponents',
    label: 'Opponents faced',
    description: 'Distinct other profiles seated in the same finished game.',
    availability: 'partial',
    phrase: 'faced at least {n} different opponent{s}',
  },
  {
    key: 'rooms',
    label: 'Rooms played in',
    description: 'Distinct game rooms this profile has finished a game in.',
    availability: 'planned',
    phrase: 'played in at least {n} different room{s}',
  },
] as const

const COUNTER_KEYS = new Set(COUNTERS.map((c) => c.key))
const DISTINCT_KEYS = new Set(DISTINCT_SETS.map((d) => d.key))

/** True when a counter key is one the engine knows how to emit or plans to. */
export function isKnownCounter(key: string): boolean {
  return COUNTER_KEYS.has(key)
}

export function isKnownDistinctSet(key: string): boolean {
  return DISTINCT_KEYS.has(key)
}

/**
 * Counters and sets that will actually fire today.
 *
 * The admin UI should offer these first and mark the rest, because a rule referencing a
 * `planned` measure is indistinguishable at runtime from a typo: both read as zero, both
 * produce a trophy nobody can ever earn, and neither raises an error anywhere.
 */
export function liveCounters(): CounterDef[] {
  return COUNTERS.filter((c) => c.availability !== 'planned')
}

export function liveDistinctSets(): DistinctDef[] {
  return DISTINCT_SETS.filter((d) => d.availability !== 'planned')
}
