/**
 * The counter vocabulary — what a trophy rule is allowed to talk about.
 *
 * THIS FILE IS THE PRODUCT SURFACE, not the trophy list. A trophy is a row in `trophies`
 * that an admin can write; a *counter* is a measurement the server emits, and only code can
 * add one. So the breadth here decides how much can be built without a deploy:
 *
 *   - "Win 25 games"            → composable today, because `games_won` exists
 *   - "Win without drawing"     → needs a `wins_no_draw` counter emitted by the card games
 *
 * The registry is exported so `/admin/trophies` can *show* the vocabulary while someone is
 * writing a rule. Without that, "admin-editable" quietly means "editable if you remember the
 * counter names", and the first typo produces a trophy that is simply never earned — with no
 * error, because an unknown counter reads as zero by design.
 *
 * Adding a counter here does NOT make it real. It has to be emitted by the award pass too.
 * `availability` records how far along each one is, so the admin UI can grey out the ones that
 * would never fire rather than offering a rule that silently can't be satisfied.
 */

export type CounterScope =
  /** Tracked per game type, and also aggregated globally. */
  | 'per-game'
  /** Only meaningful across all games. */
  | 'global'

export type CounterAvailability =
  /** Emitted for every game type today. */
  | 'universal'
  /**
   * Emitted only where the server can actually determine it. `games_won` is the live example:
   * there is no universal winner on this stack, so a "win" rule silently never fires for a
   * game whose outcome the server can't resolve. `./outcome.ts` maps the 16 game types where
   * it can — call `gameTypesWithWinners()` for the current list rather than hardcoding it, and
   * warn in the admin UI when a rule targets a game type outside it.
   */
  | 'partial'
  /** Declared for the catalog's benefit, not yet emitted anywhere. */
  | 'planned'

export type CounterDef = {
  key: string
  label: string
  description: string
  scope: CounterScope
  availability: CounterAvailability
  /**
   * How this measure reads in a sentence, with `{n}` for the threshold and `{s}` for a plural
   * "s". Exists so the admin editor can say "won at least 25 games" instead of "games won of at
   * least 25" — the whole point of the sentence is that someone can check the rule without
   * knowing the format, and that only works if it reads like English.
   */
  phrase: string
}

export type DistinctDef = {
  key: string
  label: string
  description: string
  availability: CounterAvailability
  /** See `CounterDef.phrase`. */
  phrase: string
}

/**
 * Scalar counters, addressable by `{ type: 'counter', counter: <key> }`.
 *
 * Deliberately broader than the launch catalog needs. Emitting a counter nobody uses yet costs
 * one key in a jsonb blob; discovering later that you need it costs a deploy and a backfill,
 * and the backfill is impossible because the games it would have measured are already over.
 */
export const COUNTERS: readonly CounterDef[] = [
  {
    key: 'games_played',
    label: 'Games played',
    description: 'Finished games this profile took part in as a seated player.',
    scope: 'per-game',
    availability: 'universal',
    phrase: 'finished at least {n} game{s}',
  },
  {
    key: 'games_won',
    label: 'Games won',
    description: 'Finished games this profile won outright.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s}',
  },
  {
    key: 'podium_finishes',
    label: 'Podium finishes',
    description: 'Finished in the top three of a ranked game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished in the top three at least {n} time{s}',
  },
  {
    key: 'days_played',
    label: 'Days played',
    description: 'Distinct calendar days (WAT) with at least one finished game.',
    scope: 'global',
    availability: 'universal',
    phrase: 'played on at least {n} different day{s}',
  },
  {
    key: 'longest_streak',
    label: 'Longest streak',
    description: 'Best run of consecutive days played.',
    scope: 'global',
    availability: 'universal',
    phrase: 'reached a streak of at least {n} day{s} in a row',
  },
  {
    key: 'big_room_games',
    label: 'Big-room games',
    description: 'Finished games with eight or more seated players.',
    scope: 'per-game',
    availability: 'universal',
    phrase: 'finished at least {n} game{s} with 8 or more players',
  },
  {
    key: 'late_night_games',
    label: 'Late-night games',
    description: 'Games finished between midnight and 5am, local to the room.',
    scope: 'global',
    availability: 'universal',
    phrase: 'finished at least {n} game{s} after midnight',
  },
  {
    key: 'host_games',
    label: 'Games hosted',
    description: 'Finished games this profile hosted.',
    scope: 'per-game',
    availability: 'planned',
    phrase: 'hosted at least {n} game{s}',
  },
  {
    key: 'comeback_wins',
    label: 'Comeback wins',
    description: 'Won after being last at any scored checkpoint.',
    scope: 'per-game',
    availability: 'planned',
    phrase: 'won at least {n} game{s} after being last',
  },
  {
    key: 'perfect_games',
    label: 'Perfect games',
    description: 'Finished with a flawless score by that game’s own definition.',
    scope: 'per-game',
    availability: 'planned',
    phrase: 'finished at least {n} perfect game{s}',
  },
  // ── Trivia ──────────────────────────────────────────────────────────────────────────────
  // Emitted by src/lib/trophies/game-facts/trivia.ts, derived at finish from `trivia_answers`.
  // `partial` because they only ever fire for Trivia — a rule using one against another game
  // would parse and save and then never be earned, which the admin UI warns about.
  // Note the `_games` / `_wins` suffixes: these are counted ONCE PER GAME, not per event, so
  // "hit a ten-answer run in at least 1 game" is the readable form. Lifetime totals (correct
  // answers) are the exception and carry no suffix.
  {
    key: 'trivia_correct_answers',
    label: 'Trivia — correct answers',
    description: 'Questions answered correctly, across every Trivia game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'answered at least {n} Trivia question{s} correctly',
  },
  {
    key: 'trivia_first_correct_games',
    label: 'Trivia — beat everyone to it',
    description: 'Games where you were the first player to answer a question correctly.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been first to a correct answer in at least {n} game{s}',
  },
  {
    key: 'trivia_speed_demon_games',
    label: 'Trivia — first on five',
    description: 'Games where you were first correct on five or more questions.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been first correct five times in at least {n} game{s}',
  },
  {
    key: 'trivia_clean_sweep_games',
    label: 'Trivia — first on everything',
    description: 'Games where you were first correct on every question (5+ questions).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept every question in at least {n} game{s}',
  },
  {
    key: 'trivia_buzzer_beater_games',
    label: 'Trivia — buzzer beater',
    description: 'Games with a correct answer inside the last two seconds.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'answered on the buzzer in at least {n} game{s}',
  },
  {
    key: 'trivia_lightning_games',
    label: 'Trivia — lightning',
    description: 'Games where your correct answers averaged under three seconds.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'averaged under three seconds in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_3_games',
    label: 'Trivia — three in a row',
    description: 'Games with a run of three consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a three-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_5_games',
    label: 'Trivia — five in a row',
    description: 'Games with a run of five consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a five-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_10_games',
    label: 'Trivia — ten in a row',
    description: 'Games with a run of ten consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a ten-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_streak_20_games',
    label: 'Trivia — twenty in a row',
    description: 'Games with a run of twenty consecutive correct answers.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a twenty-answer run in at least {n} game{s}',
  },
  {
    key: 'trivia_full_marks_games',
    label: 'Trivia — full marks',
    description: 'Games of five or more questions answered perfectly.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored full marks in at least {n} game{s}',
  },
  {
    key: 'trivia_perfect_10q_games',
    label: 'Trivia — perfect ten',
    description: 'Games of ten or more questions answered perfectly.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been perfect over ten questions at least {n} time{s}',
  },
  {
    key: 'trivia_flawless_wins',
    label: 'Trivia — flawless victory',
    description: 'Wins with perfect accuracy over fifteen or more questions.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won flawlessly at least {n} time{s}',
  },
  {
    key: 'trivia_custom_set_games',
    label: 'Trivia — custom sets',
    description: 'Games played on an uploaded question set.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} custom-set game{s}',
  },
  {
    key: 'trivia_big_room_15',
    label: 'Trivia — big room',
    description: 'Games played with fifteen or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} game{s} with 15+ players',
  },
  {
    key: 'trivia_packed_house_wins',
    label: 'Trivia — packed house',
    description: 'Wins in games of twenty or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with 20+ players',
  },
  {
    key: 'trivia_comeback_wins',
    label: 'Trivia — comeback',
    description: 'Wins from outside the top three at the halfway point.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'come from behind to win at least {n} time{s}',
  },
  {
    key: 'trivia_wire_to_wire_wins',
    label: 'Trivia — wire to wire',
    description: 'Wins where you led after every single question.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'led wire-to-wire in at least {n} win{s}',
  },
  // ── Codewords — from codewords_guesses + player_roles at finish ───────────────────────────────────────────────
  {
    key: 'codewords_own_word_guesses',
    label: 'Own words found',
    description: 'Your team\u2019s own words that you personally uncovered.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'found at least {n} of your team\u2019s words',
  },
  {
    key: 'codewords_neutral_guesses',
    label: 'Neutral words hit',
    description: 'Bystander words you guessed.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit at least {n} neutral word{s}',
  },
  {
    key: 'codewords_opponent_guesses',
    label: 'Opponent words hit',
    description: 'Words you guessed that belonged to the other team.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'handed the other team at least {n} word{s}',
  },
  {
    key: 'codewords_assassin_guesses',
    label: 'Assassin hit',
    description: 'Games ended by you guessing the assassin.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit the assassin at least {n} time{s}',
  },
  {
    key: 'codewords_clean_turns',
    label: 'Clean turns',
    description: 'Turns where your team guessed only its own words.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'completed at least {n} clean turn{s}',
  },
  {
    key: 'codewords_clue2_full',
    label: 'Clue for two, all found',
    description: 'Games where a clue for two had both words found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for two in at least {n} game{s}',
  },
  {
    key: 'codewords_clue3_full',
    label: 'Clue for three, all found',
    description: 'Games where a clue for three had all three found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for three in at least {n} game{s}',
  },
  {
    key: 'codewords_clue4_full',
    label: 'Clue for four, all found',
    description: 'Games where a clue for four had all four found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for four in at least {n} game{s}',
  },
  {
    key: 'codewords_clue5_full',
    label: 'Clue for five, all found',
    description: 'Games where a clue for five had all five found.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a full clue for five in at least {n} game{s}',
  },
  {
    key: 'codewords_run4_guesses',
    label: 'Four on one clue',
    description: 'Games where you personally found four words on a single clue.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'found four on one clue in at least {n} game{s}',
  },
  {
    key: 'codewords_run5_guesses',
    label: 'Five on one clue',
    description: 'Games where you personally found five words on a single clue.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'found five on one clue in at least {n} game{s}',
  },
  {
    key: 'codewords_spymaster_wins',
    label: 'Wins as spymaster',
    description: 'Wins where you finished the game as spymaster.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as spymaster',
  },
  {
    key: 'codewords_operative_wins',
    label: 'Wins as operative',
    description: 'Wins where you finished the game as operative.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as operative',
  },
  {
    key: 'codewords_assassin_dodged_wins',
    label: 'Assassin dodged',
    description: 'Wins where the assassin was never turned over.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} time{s} with the assassin untouched',
  },
  {
    key: 'codewords_perfect_wins',
    label: 'Perfect game',
    description: 'Wins where your team never guessed a wrong word.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} without a wrong guess',
  },
  {
    key: 'codewords_sweep_wins',
    label: 'Sweep',
    description: 'Wins in four clue runs or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept a win in at least {n} game{s}',
  },
  {
    key: 'codewords_flawless_sweep_wins',
    label: 'Flawless sweep',
    description: 'Wins in three runs with no wrong guesses.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'managed a flawless sweep at least {n} time{s}',
  },
  {
    key: 'codewords_clutch_wins',
    label: 'Clutch',
    description: 'Wins with the opponent one word from taking it.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won from the brink at least {n} time{s}',
  },
  {
    key: 'codewords_comeback_wins',
    label: 'Comeback',
    description: 'Wins from three or more words behind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'come from behind to win at least {n} time{s}',
  },
  // ── Chess — from replaying chess_sessions.pgn at finish ───────────────────────────────────────────────
  {
    key: 'chess_captures',
    label: 'Pieces captured',
    description: 'Enemy pieces you have taken.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} piece{s}',
  },
  {
    key: 'chess_checks_given',
    label: 'Checks given',
    description: 'Moves of yours that put the enemy king in check.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'given check at least {n} time{s}',
  },
  {
    key: 'chess_castles',
    label: 'Castled',
    description: 'Times you have castled.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'castled at least {n} time{s}',
  },
  {
    key: 'chess_queenside_castles',
    label: 'Castled queenside',
    description: 'Times you have castled long.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'castled queenside at least {n} time{s}',
  },
  {
    key: 'chess_promotions',
    label: 'Pawns promoted',
    description: 'Pawns you have promoted.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'promoted at least {n} pawn{s}',
  },
  {
    key: 'chess_underpromotions',
    label: 'Underpromotions',
    description: 'Pawns promoted to something other than a queen.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'underpromoted at least {n} time{s}',
  },
  {
    key: 'chess_queens_captured',
    label: 'Queens captured',
    description: 'Enemy queens you have taken.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} queen{s}',
  },
  {
    key: 'chess_en_passant',
    label: 'En passant',
    description: 'En passant captures you have made.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured en passant at least {n} time{s}',
  },
  {
    key: 'chess_forks',
    label: 'Forks',
    description: 'Checks that also attacked another piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'forked your opponent at least {n} time{s}',
  },
  {
    key: 'chess_double_checks',
    label: 'Double checks',
    description: 'Positions where two of your pieces checked at once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'delivered at least {n} double check{s}',
  },
  {
    key: 'chess_endgame_reached',
    label: 'Endgame reached',
    description: 'Games that reached six pieces or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached an endgame in at least {n} game{s}',
  },
  {
    key: 'chess_two_queens_games',
    label: 'Two queens',
    description: 'Games where you had two queens on the board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'had two queens in at least {n} game{s}',
  },
  {
    key: 'chess_wins_checkmate',
    label: 'Wins by checkmate',
    description: 'Games won by delivering mate.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won by checkmate at least {n} time{s}',
  },
  {
    key: 'chess_wins_timeout',
    label: 'Wins on time',
    description: 'Games won by the opponent running out of clock.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won on time at least {n} time{s}',
  },
  {
    key: 'chess_wins_resignation',
    label: 'Wins by resignation',
    description: 'Games the opponent resigned or abandoned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won by resignation at least {n} time{s}',
  },
  {
    key: 'chess_wins_under_10s',
    label: 'Wins under pressure',
    description: 'Timed wins with under ten seconds left on your own clock.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won with under ten seconds left at least {n} time{s}',
  },
  {
    key: 'chess_wins_blitz',
    label: 'Blitz wins',
    description: 'Wins in a three-minute game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} blitz game{s}',
  },
  {
    key: 'chess_wins_after_queen_loss',
    label: 'Wins without your queen',
    description: 'Wins in games where your queen was captured.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} after losing your queen',
  },
  {
    key: 'chess_wins_material_down_move20',
    label: 'Wins from behind',
    description: 'Wins while behind on material at move twenty.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won from material down at least {n} time{s}',
  },
  {
    key: 'chess_wins_clean_sheet',
    label: 'Clean sheet',
    description: 'Wins without losing a single piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without losing a piece at least {n} time{s}',
  },
  {
    key: 'chess_wins_back_rank',
    label: 'Back-rank mates',
    description: 'Wins by mating on the back rank.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'delivered at least {n} back-rank mate{s}',
  },
  {
    key: 'chess_wins_knight_mate',
    label: 'Knight mates',
    description: 'Wins where a knight delivered mate.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'mated with a knight at least {n} time{s}',
  },
  {
    key: 'chess_wins_mate_in_20',
    label: 'Quick mates',
    description: 'Wins by checkmate in twenty moves or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'mated inside twenty moves at least {n} time{s}',
  },
  {
    key: 'chess_wins_mate_in_12',
    label: 'Miniatures',
    description: 'Wins by checkmate in twelve moves or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'mated inside twelve moves at least {n} time{s}',
  },
  {
    key: 'chess_wins_60_moves',
    label: 'Long games',
    description: 'Wins in games lasting sixty moves or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a sixty-move game at least {n} time{s}',
  },
  {
    key: 'chess_draws_stalemate',
    label: 'Stalemates',
    description: 'Games that ended in stalemate.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'reached stalemate at least {n} time{s}',
  },
  // ── Yahtzee — from the persisted 13-cell scorecard ───────────────────────────────────────────────
  {
    key: 'yahtzee_full_house_scored',
    label: 'Full house',
    description: 'Games where you scored a full house.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a full house in at least {n} game{s}',
  },
  {
    key: 'yahtzee_small_straight_scored',
    label: 'Small straight',
    description: 'Games where you scored a small straight.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a small straight in at least {n} game{s}',
  },
  {
    key: 'yahtzee_large_straight_scored',
    label: 'Large straight',
    description: 'Games where you scored a large straight.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a large straight in at least {n} game{s}',
  },
  {
    key: 'yahtzee_three_kind_scored',
    label: 'Three of a kind',
    description: 'Games where you scored three of a kind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored three of a kind in at least {n} game{s}',
  },
  {
    key: 'yahtzee_four_kind_scored',
    label: 'Four of a kind',
    description: 'Games where you scored four of a kind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored four of a kind in at least {n} game{s}',
  },
  {
    key: 'yahtzee_chance_25_plus',
    label: 'Chance 25+',
    description: 'Games where Chance scored twenty-five or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 25+ in Chance in at least {n} game{s}',
  },
  {
    key: 'yahtzee_chance_perfect_30',
    label: 'Perfect chance',
    description: 'Games where Chance scored the maximum thirty.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'maxed Chance in at least {n} game{s}',
  },
  {
    key: 'yahtzee_scored_yahtzee',
    label: 'Yahtzee scored',
    description: 'Games where you took a Yahtzee for fifty.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored a Yahtzee in at least {n} game{s}',
  },
  {
    key: 'yahtzee_upper_bonus_games',
    label: 'Upper bonus',
    description: 'Games where you earned the thirty-five point upper bonus.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'earned the upper bonus in at least {n} game{s}',
  },
  {
    key: 'yahtzee_upper_70_plus',
    label: 'Upper cut',
    description: 'Games with seventy or more in the upper section.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 70+ upstairs in at least {n} game{s}',
  },
  {
    key: 'yahtzee_sixes_24_plus',
    label: 'Sixes full',
    description: 'Games where Sixes scored twenty-four or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 24+ in Sixes in at least {n} game{s}',
  },
  {
    key: 'yahtzee_four_kind_27_plus',
    label: 'Heavy hitter',
    description: 'Games where Four of a Kind scored twenty-seven or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 27+ in four of a kind in at least {n} game{s}',
  },
  {
    key: 'yahtzee_both_straights_games',
    label: 'Both straights',
    description: 'Games where you scored both straights.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored both straights in at least {n} game{s}',
  },
  {
    key: 'yahtzee_no_zero_games',
    label: 'No zeros',
    description: 'Games where every category scored above zero.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'filled a card with no zeros at least {n} time{s}',
  },
  {
    key: 'yahtzee_lower_sweep_games',
    label: 'Full sweep',
    description: 'Games where every lower category scored above zero.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept the lower section at least {n} time{s}',
  },
  {
    key: 'yahtzee_flawless_card_games',
    label: 'Flawless card',
    description: 'Games with the upper bonus and no zeros anywhere.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'filled a flawless card at least {n} time{s}',
  },
  {
    key: 'yahtzee_games_200_plus',
    label: 'Century',
    description: 'Games finishing on two hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 200+ at least {n} time{s}',
  },
  {
    key: 'yahtzee_games_250_plus',
    label: 'High roller',
    description: 'Games finishing on two hundred and fifty or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 250+ at least {n} time{s}',
  },
  {
    key: 'yahtzee_games_300_plus',
    label: 'Three hundred club',
    description: 'Games finishing on three hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 300+ at least {n} time{s}',
  },
  {
    key: 'yahtzee_multiplayer_wins',
    label: 'Wins',
    description: 'Multiplayer games won.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s}',
  },
  {
    key: 'yahtzee_big_table_wins',
    label: 'Table beater',
    description: 'Wins with four or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with 4+ players',
  },
  {
    key: 'chess_wins_smothered',
    label: 'Chess — smothered mate',
    description: 'Wins by smothered mate: a knight mates a king walled in by its own pieces.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'delivered at least {n} smothered mate{s}',
  },
  {
    key: 'chess_wins_queen_sac',
    label: 'Chess — won without your queen',
    description: 'Wins where your queen was captured and the opponent kept theirs.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} a queen down',
  },
  {
    key: 'yahtzee_bonus_earned',
    label: 'Yahtzee — bonus earned',
    description: 'Games where you earned at least one 100-point Yahtzee bonus.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'earned a Yahtzee bonus in at least {n} game{s}',
  },
  {
    key: 'yahtzee_joker_used',
    label: 'Yahtzee — Joker scored',
    description: 'Games where you scored a Yahtzee under the Joker rule.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'used the Joker rule in at least {n} game{s}',
  },
  // ── Crazy Eights — from crazy_eights_player_hands.stats at finish ───────────────────────────────────────────
  {
    key: 'c8_eights_played',
    label: 'Crazy Eights — 8s played',
    description: '8s played across Crazy Eights games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Crazy Eight{s}',
  },
  {
    key: 'c8_pick_twos_played',
    label: 'Crazy Eights — Pick Twos',
    description: '2s played as a Pick Two.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Pick Two{s}',
  },
  {
    key: 'c8_pick_twos_stacked',
    label: 'Crazy Eights — Pick Twos stacked',
    description: '2s stacked onto an active Pick Two.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'stacked at least {n} Pick Two{s}',
  },
  {
    key: 'c8_skips_played',
    label: 'Crazy Eights — Skips',
    description: 'Jacks or Aces played as a Skip.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Skip{s}',
  },
  {
    key: 'c8_reverses_played',
    label: 'Crazy Eights — Reverses',
    description: 'Queens played as a Reverse.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Reverse{s}',
  },
  {
    key: 'c8_jokers_played',
    label: 'Crazy Eights — Jokers',
    description: 'Jokers played.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} Joker{s}',
  },
  {
    key: 'c8_cards_drawn',
    label: 'Crazy Eights — cards drawn',
    description: 'Cards drawn from the pile.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'drew at least {n} card{s}',
  },
  {
    key: 'c8_suit_changes_3_games',
    label: 'Crazy Eights — suit changer',
    description: 'Games where you changed the suit three times.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'changed the suit three times in at least {n} game{s}',
  },
  {
    key: 'c8_drew_5_games',
    label: 'Crazy Eights — deck diver',
    description: 'Games where you drew five cards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'drew five cards in at least {n} game{s}',
  },
  {
    key: 'c8_three_eights_games',
    label: 'Crazy Eights — eight ball',
    description: 'Games where you played three 8s.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three 8s in at least {n} game{s}',
  },
  {
    key: 'c8_suit_run_4_games',
    label: 'Crazy Eights — suit run',
    description: 'Games with four same-suit cards in a row.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played four same-suit cards in a row in at least {n} game{s}',
  },
  {
    key: 'c8_rank_run_3_games',
    label: 'Crazy Eights — rank run',
    description: 'Games with three same-rank cards in a row.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three same-rank cards in a row in at least {n} game{s}',
  },
  {
    key: 'c8_all_suits_games',
    label: 'Crazy Eights — full deck',
    description: 'Games where you played every suit.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played every suit in at least {n} game{s}',
  },
  {
    key: 'c8_three_skips_games',
    label: 'Crazy Eights — skip to the end',
    description: 'Games where you played three Skips.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three Skips in at least {n} game{s}',
  },
  {
    key: 'c8_two_queens_games',
    label: 'Crazy Eights — round trip',
    description: 'Games where you played two Queens.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played two Queens in at least {n} game{s}',
  },
  {
    key: 'c8_no_pick_two_games',
    label: 'Crazy Eights — untouched',
    description: 'Games finished without taking a Pick Two.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished at least {n} game{s} without taking a Pick Two',
  },
  {
    key: 'c8_quickfire_wins',
    label: 'Crazy Eights — quickfire',
    description: 'Wins in eight turns or fewer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} in eight turns or fewer',
  },
  {
    key: 'c8_survivor_wins',
    label: 'Crazy Eights — survivor',
    description: 'Wins after drawing ten or more cards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} after drawing ten or more cards',
  },
  {
    key: 'c8_comeback_wins',
    label: 'Crazy Eights — comeback',
    description: 'Wins after holding twelve or more cards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} after holding twelve or more cards',
  },
  {
    key: 'c8_full_table_wins',
    label: 'Crazy Eights — full table',
    description: 'Wins in a six-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} six-player game{s}',
  },
  {
    key: 'c8_suit_master_wins',
    label: 'Crazy Eights — suit master',
    description: 'Wins having played every suit and an 8.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} having played every suit and an 8',
  },
  {
    key: 'c8_suit_sweep_wins',
    label: 'Crazy Eights — suit sweep',
    description: 'Wins having played every suit, an 8 and a Joker.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} having played every suit, an 8 and a Joker',
  },
  {
    key: 'c8_flawless_wins',
    label: 'Crazy Eights — flawless',
    description: 'Wins without drawing a card.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} without drawing a card',
  },
  {
    key: 'c8_eight_finish_wins',
    label: 'Crazy Eights — eight finish',
    description: 'Wins on an 8.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on an 8',
  },
  {
    key: 'c8_joker_finish_wins',
    label: 'Crazy Eights — joker finish',
    description: 'Wins on a Joker.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on a Joker',
  },
  // ── Ludo — from ludo_player_state.game_counters at finish ───────────────────────────────────────────
  {
    key: 'ludo_sixes_rolled',
    label: 'Ludo — sixes rolled',
    description: 'Sixes rolled across Ludo games.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled a six at least {n} time{s}',
  },
  {
    key: 'ludo_double_sixes',
    label: 'Ludo — double sixes',
    description: 'Double sixes rolled.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled a double six at least {n} time{s}',
  },
  {
    key: 'ludo_captures_made',
    label: 'Ludo — captures',
    description: 'Opponent pieces captured.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} piece{s}',
  },
  {
    key: 'ludo_safe_landings',
    label: 'Ludo — safe landings',
    description: 'Landings on a safe square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed on a safe square at least {n} time{s}',
  },
  {
    key: 'ludo_pieces_deployed',
    label: 'Ludo — pieces deployed',
    description: 'Pieces brought out of the yard.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'brought out at least {n} piece{s}',
  },
  {
    key: 'ludo_times_captured',
    label: 'Ludo — pieces lost',
    description: 'Your pieces captured by opponents.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'lost at least {n} piece{s} to capture',
  },
  {
    key: 'ludo_six_sense_games',
    label: 'Ludo — three sixes',
    description: 'Games where you rolled three sixes.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled three sixes in at least {n} game{s}',
  },
  {
    key: 'ludo_dice_hot_games',
    label: 'Ludo — five sixes',
    description: 'Games where you rolled five sixes.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'rolled five sixes in at least {n} game{s}',
  },
  {
    key: 'ludo_full_deploy_games',
    label: 'Ludo — full deployment',
    description: 'Games with all four pieces out at once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'had all four pieces out in at least {n} game{s}',
  },
  {
    key: 'ludo_shield_games',
    label: 'Ludo — shield',
    description: 'Games where you formed a two-piece shield.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'formed a two-piece shield in at least {n} game{s}',
  },
  {
    key: 'ludo_double_capture_games',
    label: 'Ludo — double capture',
    description: 'Games where you captured two with one move.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured two with one move in at least {n} game{s}',
  },
  {
    key: 'ludo_sent_packing_games',
    label: 'Ludo — sent packing',
    description: 'Games where you captured one opponent three times.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured one opponent three times in at least {n} game{s}',
  },
  {
    key: 'ludo_escape_artist_games',
    label: 'Ludo — escape artist',
    description: 'Games where a captured piece still got home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'brought a captured piece home in at least {n} game{s}',
  },
  {
    key: 'ludo_fast_start_games',
    label: 'Ludo — fast start',
    description: 'Games where you deployed on the first roll.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'deployed on the first roll in at least {n} game{s}',
  },
  {
    key: 'ludo_gridlock_games',
    label: 'Ludo — gridlock',
    description: 'Games where you forfeited on three double sixes.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'forfeited on three double sixes in at least {n} game{s}',
  },
  {
    key: 'ludo_pieces_home_1',
    label: 'Ludo — one home',
    description: 'Games where you got a piece home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got a piece home in at least {n} game{s}',
  },
  {
    key: 'ludo_pieces_home_2',
    label: 'Ludo — two home',
    description: 'Games where you got two pieces home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got two pieces home in at least {n} game{s}',
  },
  {
    key: 'ludo_pieces_home_3',
    label: 'Ludo — three home',
    description: 'Games where you got three pieces home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got three pieces home in at least {n} game{s}',
  },
  {
    key: 'ludo_clean_sweep_games',
    label: 'Ludo — clean sweep',
    description: 'Games where you captured five pieces.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured five in a game at least {n} time{s}',
  },
  {
    key: 'ludo_untouched_wins',
    label: 'Ludo — untouchable',
    description: 'Wins without losing a piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without losing a piece at least {n} time{s}',
  },
  {
    key: 'ludo_comeback_wins',
    label: 'Ludo — comeback',
    description: 'Wins after a full yard-out.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won after a full yard-out at least {n} time{s}',
  },
  {
    key: 'ludo_runaway_games',
    label: 'Ludo — runaway',
    description: 'Wins before a rival got two pieces home.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won before a rival got two home at least {n} time{s}',
  },
  {
    key: 'ludo_four_corners_wins',
    label: 'Ludo — four corners',
    description: 'Wins in a four-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a four-player game at least {n} time{s}',
  },
  {
    key: 'ludo_perfect_run_wins',
    label: 'Ludo — perfect run',
    description: 'Untouched wins in a four-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a four-player game untouched at least {n} time{s}',
  },
  {
    key: 'ludo_untouched_sweep_wins',
    label: 'Ludo — untouched sweep',
    description: 'Wins with five or more captures and none lost.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won with 5+ captures and none lost at least {n} time{s}',
  },
  // ── Monopoly — from the finished board + player_state ───────────────────────────────────────────
  {
    key: 'monopoly_passed_go',
    label: 'Monopoly — passed GO',
    description: 'Games where you passed GO at least once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'passed GO in at least {n} game{s}',
  },
  {
    key: 'monopoly_three_properties',
    label: 'Monopoly — three properties',
    description: 'Games ending with three or more properties owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned three or more properties in at least {n} game{s}',
  },
  {
    key: 'monopoly_ten_properties',
    label: 'Monopoly — ten properties',
    description: 'Games ending with ten or more properties owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned ten or more properties in at least {n} game{s}',
  },
  {
    key: 'monopoly_full_color_set',
    label: 'Monopoly — colour set',
    description: 'Games where you owned a full colour group.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'completed a colour set in at least {n} game{s}',
  },
  {
    key: 'monopoly_both_utilities',
    label: 'Monopoly — both utilities',
    description: 'Games ending with both utilities owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned both utilities in at least {n} game{s}',
  },
  {
    key: 'monopoly_two_stations',
    label: 'Monopoly — two stations',
    description: 'Games ending with two or more stations owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned two or more stations in at least {n} game{s}',
  },
  {
    key: 'monopoly_all_stations',
    label: 'Monopoly — all stations',
    description: 'Games ending with all four stations owned.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned all four stations in at least {n} game{s}',
  },
  {
    key: 'monopoly_blue_chip',
    label: 'Monopoly — blue chip',
    description: 'Games where you owned both the dark blue and green monopolies.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'held the blue-chip monopolies in at least {n} game{s}',
  },
  {
    key: 'monopoly_one_side',
    label: 'Monopoly — whole side',
    description: 'Games where you owned every property on one side of the board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'owned a whole side in at least {n} game{s}',
  },
  {
    key: 'monopoly_three_houses',
    label: 'Monopoly — three houses',
    description: 'Games where you built three houses on a single property.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'built three houses in at least {n} game{s}',
  },
  {
    key: 'monopoly_naija_wins',
    label: 'Monopoly — Naija win',
    description: 'Wins on the Naija board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on the Naija board',
  },
  {
    key: 'monopoly_london_wins',
    label: 'Monopoly — London win',
    description: 'Wins on the classic London board.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} on the London board',
  },
  {
    key: 'monopoly_last_one_standing',
    label: 'Monopoly — last one standing',
    description: 'Wins of three or more players by bankrupting everyone else.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been last one standing in at least {n} game{s}',
  },
  // ── Text Charades — from describe_it_words + describe_it_guesses at finish ───────────────────────────────────────────────
  {
    key: 'describe_it_words_guessed',
    label: 'Text Charades — words guessed',
    description: 'Words correctly guessed, across every Text Charades game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'guessed at least {n} word{s}',
  },
  {
    key: 'describe_it_describer_turns',
    label: 'Text Charades — describer turns',
    description: 'Turns taken in the describer role.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'described at least {n} time{s}',
  },
  {
    key: 'describe_it_custom_set_games',
    label: 'Text Charades — custom words',
    description: 'Games played on an uploaded word list.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} custom-word game{s}',
  },
  {
    key: 'describe_it_wordsmith_games',
    label: 'Text Charades — wordsmith',
    description: 'Games where you guessed ten or more words.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'guessed ten words in at least {n} game{s}',
  },
  {
    key: 'describe_it_big_room_12',
    label: 'Text Charades — big room',
    description: 'Games played with twelve or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} game{s} with 12+ players',
  },
  {
    key: 'describe_it_all_rounder_games',
    label: 'Text Charades — all rounder',
    description: 'Games where you both described and guessed.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'described and guessed in at least {n} game{s}',
  },
  {
    key: 'describe_it_big_team_games',
    label: 'Text Charades — team player',
    description: 'Games played on a team of three or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} game{s} on a team of 3+',
  },
  {
    key: 'describe_it_round_guess_3',
    label: 'Text Charades — hat trick',
    description: 'Games where you guessed three words in one round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'guessed three in a round in at least {n} game{s}',
  },
  {
    key: 'describe_it_guess_run_3',
    label: 'Text Charades — mind meld',
    description: 'Games with three words guessed in a row for one describer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a three-word run in at least {n} game{s}',
  },
  {
    key: 'describe_it_guess_run_5',
    label: 'Text Charades — telepathy',
    description: 'Games with five words guessed in a row for one describer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hit a five-word run in at least {n} game{s}',
  },
  {
    key: 'describe_it_describer_5_round',
    label: 'Text Charades — five alive',
    description: 'Games with five words guessed in one describer round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got five as describer in at least {n} game{s}',
  },
  {
    key: 'describe_it_describer_8_round',
    label: 'Text Charades — marathon',
    description: 'Games with eight words guessed in one describer round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got eight as describer in at least {n} game{s}',
  },
  {
    key: 'describe_it_describer_10_round',
    label: 'Text Charades — ten in a round',
    description: 'Games with ten words guessed in one describer round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got ten as describer in at least {n} game{s}',
  },
  {
    key: 'describe_it_describer_12_round',
    label: 'Text Charades — twelve in a round',
    description: 'Games with twelve words guessed in one describer round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'got twelve as describer in at least {n} game{s}',
  },
  {
    key: 'describe_it_perfect_round_games',
    label: 'Text Charades — perfect round',
    description: 'Games with a describer round where every word (3+) was guessed, none skipped.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'had a perfect describer round in at least {n} game{s}',
  },
  {
    key: 'describe_it_packed_house_wins',
    label: 'Text Charades — packed house',
    description: 'Wins in games of sixteen or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with 16+ players',
  },
  {
    key: 'describe_it_comeback_wins',
    label: 'Text Charades — comeback',
    description: 'Wins from strictly last place at the halfway point.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'come from last to win at least {n} time{s}',
  },
  {
    key: 'describe_it_clean_sweep_wins',
    label: 'Text Charades — clean sweep',
    description: 'Wins where your team led every round.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'led wire-to-wire in at least {n} win{s}',
  },
  {
    key: 'describe_it_flawless_wins',
    label: 'Text Charades — flawless',
    description: 'Wins where your team never had a word skipped.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without a skipped word at least {n} time{s}',
  },
  // ── Mafia — from mafia_player_states + winning_team at finish ───────────────────────────────────────────────
  {
    key: 'mafia_mafia_games',
    label: 'Mafia — joined the family',
    description: 'Games played on the Mafia side.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} game{s} on the Mafia side',
  },
  {
    key: 'mafia_survivor_games',
    label: 'Mafia — survivor',
    description: 'Games survived to the end.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'survived to the end of at least {n} game{s}',
  },
  {
    key: 'mafia_lynched_games',
    label: 'Mafia — lynched',
    description: 'Games where you were voted out.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been voted out at least {n} time{s}',
  },
  {
    key: 'mafia_bodyguard_hits',
    label: 'Mafia — took the bullet',
    description: 'Games where you took a kill as the Bodyguard.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'taken a hit as the Bodyguard in at least {n} game{s}',
  },
  {
    key: 'mafia_last_villager',
    label: 'Mafia — last villager',
    description: 'Wins as the last surviving villager.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'been the last surviving villager at least {n} time{s}',
  },
  {
    key: 'mafia_big_game_12',
    label: 'Mafia — big game',
    description: 'Games played with twelve or more players.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} game{s} with 12+ players',
  },
  {
    key: 'mafia_full_house_16',
    label: 'Mafia — full house',
    description: 'Full sixteen-player games played.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} full 16-player game{s}',
  },
  {
    key: 'mafia_village_wins',
    label: 'Mafia — village win',
    description: 'Wins with the Village.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with the Village',
  },
  {
    key: 'mafia_mafia_wins',
    label: 'Mafia — family win',
    description: 'Wins with the Mafia.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} with the Mafia',
  },
  {
    key: 'mafia_jester_wins',
    label: 'Mafia — jester win',
    description: 'Wins as the Jester.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as the Jester',
  },
  {
    key: 'mafia_serial_killer_wins',
    label: 'Mafia — serial killer win',
    description: 'Wins as the Serial Killer.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as the Serial Killer',
  },
  {
    key: 'mafia_arsonist_wins',
    label: 'Mafia — arsonist win',
    description: 'Wins as the Arsonist.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as the Arsonist',
  },
  {
    key: 'mafia_lovers_wins',
    label: 'Mafia — lovers win',
    description: 'Wins as a Lover.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} game{s} as a Lover',
  },
  {
    key: 'mafia_clean_sweep_wins',
    label: 'Mafia — clean sweep',
    description: 'Mafia wins with every member alive.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won with the Mafia intact at least {n} time{s}',
  },
  // ── Scrabble — from scrabble_player_state.stats + final score/rack at finish ───────────────────────────────────────────────
  {
    key: 'scrabble_opening_move_games',
    label: 'Scrabble — opening move',
    description: 'Games where you played the first word across the centre star.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'opened on the star in at least {n} game{s}',
  },
  {
    key: 'scrabble_double_letter_games',
    label: 'Scrabble — double letter',
    description: 'Games where you covered a double-letter square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'covered a double-letter square in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_letter_games',
    label: 'Scrabble — triple letter',
    description: 'Games where you covered a triple-letter square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'covered a triple-letter square in at least {n} game{s}',
  },
  {
    key: 'scrabble_double_word_games',
    label: 'Scrabble — double word',
    description: 'Games where you covered a double-word square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'covered a double-word square in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_word_games',
    label: 'Scrabble — triple word',
    description: 'Games where you covered a triple-word square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'covered a triple-word square in at least {n} game{s}',
  },
  {
    key: 'scrabble_blank_games',
    label: 'Scrabble — blank tile',
    description: 'Games where you played a blank tile.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played a blank in at least {n} game{s}',
  },
  {
    key: 'scrabble_swap_games',
    label: 'Scrabble — exchange',
    description: 'Games where you exchanged tiles.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'exchanged tiles in at least {n} game{s}',
  },
  {
    key: 'scrabble_two_word_games',
    label: 'Scrabble — crossworder',
    description: 'Games where a single play formed two or more words.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'formed two words in one play in at least {n} game{s}',
  },
  {
    key: 'scrabble_parallel_games',
    label: 'Scrabble — parallel play',
    description: 'Games where a single play formed three or more words.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'formed three words in one play in at least {n} game{s}',
  },
  {
    key: 'scrabble_hook_games',
    label: 'Scrabble — hook',
    description: 'Games where you extended a word with a single tile.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'hooked a word in at least {n} game{s}',
  },
  {
    key: 'scrabble_long_word_games',
    label: 'Scrabble — long word',
    description: 'Games where you played an eight-letter-or-longer word.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played an 8+ letter word in at least {n} game{s}',
  },
  {
    key: 'scrabble_q_no_u_games',
    label: 'Scrabble — Q without U',
    description: 'Games where you played a valid Q word with no U.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played a Q-without-U word in at least {n} game{s}',
  },
  {
    key: 'scrabble_high_value_games',
    label: 'Scrabble — high value',
    description: 'Games where you played a Z, Q, X or J on a premium square.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played a high-value tile on a premium in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_triple_games',
    label: 'Scrabble — triple-triple',
    description: 'Games where one word covered two triple-word squares.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a triple-triple in at least {n} game{s}',
  },
  {
    key: 'scrabble_bingo_games',
    label: 'Scrabble — bingo',
    description: 'Games where you played all seven tiles in one turn.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played a bingo in at least {n} game{s}',
  },
  {
    key: 'scrabble_double_bingo_games',
    label: 'Scrabble — double bingo',
    description: 'Games where you played two bingos.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played two bingos in at least {n} game{s}',
  },
  {
    key: 'scrabble_triple_bingo_games',
    label: 'Scrabble — triple bingo',
    description: 'Games where you played three bingos.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played three bingos in at least {n} game{s}',
  },
  {
    key: 'scrabble_big_play_games',
    label: 'Scrabble — big play',
    description: 'Games with a 40+ point single word.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 40+ on a word in at least {n} game{s}',
  },
  {
    key: 'scrabble_monster_play_games',
    label: 'Scrabble — monster play',
    description: 'Games with an 80+ point single word.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 80+ on a word in at least {n} game{s}',
  },
  {
    key: 'scrabble_century_word_games',
    label: 'Scrabble — century word',
    description: 'Games with a 100+ point single word.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'scored 100+ on a word in at least {n} game{s}',
  },
  {
    key: 'scrabble_half_century_games',
    label: 'Scrabble — half century',
    description: 'Games finishing on fifty or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 50+ in at least {n} game{s}',
  },
  {
    key: 'scrabble_century_games',
    label: 'Scrabble — century',
    description: 'Games finishing on two hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 200+ in at least {n} game{s}',
  },
  {
    key: 'scrabble_three_hundred_games',
    label: 'Scrabble — three hundred',
    description: 'Games finishing on three hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 300+ in at least {n} game{s}',
  },
  {
    key: 'scrabble_four_hundred_games',
    label: 'Scrabble — four hundred',
    description: 'Games finishing on four hundred or more.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished on 400+ in at least {n} game{s}',
  },
  {
    key: 'scrabble_clean_rack_games',
    label: 'Scrabble — clean rack',
    description: 'Games finished with an empty rack (went out).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'finished with an empty rack in at least {n} game{s}',
  },
  {
    key: 'scrabble_comeback_wins',
    label: 'Scrabble — comeback',
    description: 'Wins from sixty or more points behind.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won from 60+ behind at least {n} time{s}',
  },
  {
    key: 'scrabble_full_table_wins',
    label: 'Scrabble — full table',
    description: 'Wins in a four-player game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a four-player game at least {n} time{s}',
  },
  {
    key: 'scrabble_no_swap_wins',
    label: 'Scrabble — no swaps',
    description: 'Wins without exchanging tiles or passing.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without a swap or pass at least {n} time{s}',
  },
  // ── Checkers / Draughts — paired red_/black_ stats at finish ───────────────────────────────────────────────
  {
    key: 'checkers_captures',
    label: 'Checkers — pieces captured',
    description: 'Enemy pieces captured (includes Nigerian huffs).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} piece{s}',
  },
  {
    key: 'checkers_kings_made',
    label: 'Checkers — kings crowned',
    description: 'Men crowned into kings.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'crowned at least {n} king{s}',
  },
  {
    key: 'checkers_enemy_kings_captured',
    label: 'Checkers — enemy kings taken',
    description: 'Enemy kings captured.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured at least {n} enemy king{s}',
  },
  {
    key: 'checkers_five_down_games',
    label: 'Checkers — five down',
    description: 'Games where you captured five or more pieces.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured five pieces in at least {n} game{s}',
  },
  {
    key: 'checkers_double_jump_games',
    label: 'Checkers — double jump',
    description: 'Games with a two-capture turn.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a double jump in at least {n} game{s}',
  },
  {
    key: 'checkers_triple_jump_games',
    label: 'Checkers — triple jump',
    description: 'Games with a three-capture turn.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a triple jump in at least {n} game{s}',
  },
  {
    key: 'checkers_quad_jump_games',
    label: 'Checkers — quadruple jump',
    description: 'Games with a four-capture turn.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'landed a quadruple jump in at least {n} game{s}',
  },
  {
    key: 'checkers_king_me_twice_games',
    label: 'Checkers — two kings',
    description: 'Games where you held two kings at once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'held two kings at once in at least {n} game{s}',
  },
  {
    key: 'checkers_kings_court_games',
    label: 'Checkers — three kings',
    description: 'Games where you held three kings at once.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'held three kings at once in at least {n} game{s}',
  },
  {
    key: 'checkers_back_row_games',
    label: 'Checkers — home guard',
    description: 'Games where you held your back row for fifteen turns running.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'held your back row for fifteen turns in at least {n} game{s}',
  },
  {
    key: 'checkers_trade_games',
    label: 'Checkers — trade',
    description: 'Games with an even trade (recapture).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'made a trade in at least {n} game{s}',
  },
  {
    key: 'checkers_draw_games',
    label: 'Checkers — draw',
    description: 'Games played to a draw.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'drew at least {n} game{s}',
  },
  {
    key: 'checkers_blockade_wins',
    label: 'Checkers — blockade',
    description: 'Wins by leaving the opponent no legal move.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won by blockade at least {n} time{s}',
  },
  {
    key: 'checkers_total_victory_wins',
    label: 'Checkers — total victory',
    description: 'Wins by capturing every piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won by capturing every piece at least {n} time{s}',
  },
  {
    key: 'checkers_clock_watcher_wins',
    label: 'Checkers — clock watcher',
    description: 'Timed wins with under fifteen seconds left.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won with under fifteen seconds left at least {n} time{s}',
  },
  {
    key: 'checkers_untouched_wins',
    label: 'Checkers — untouched',
    description: 'Wins without losing a single piece.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won without losing a piece at least {n} time{s}',
  },
  {
    key: 'checkers_blitz_wins',
    label: 'Checkers — blitz',
    description: 'Wins in a three-minute game.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a blitz game at least {n} time{s}',
  },
  {
    key: 'checkers_comeback_wins',
    label: 'Checkers — comeback',
    description: 'Wins after being four or more pieces down.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won from a four-piece deficit at least {n} time{s}',
  },
  {
    key: 'checkers_quick_win_wins',
    label: 'Checkers — quick win',
    description: 'Wins in a dozen turns or fewer (eighteen on 10x10).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won quickly at least {n} time{s}',
  },
  {
    key: 'checkers_endgame_master_wins',
    label: 'Checkers — endgame master',
    description: 'Wins in a game that reached an endgame.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won an endgame at least {n} time{s}',
  },
  {
    key: 'checkers_flying_king_games',
    label: 'Checkers — flying king',
    description: 'Games with a four-square-plus king hop (10x10).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'flew a king across the board in at least {n} game{s}',
  },
  {
    key: 'checkers_majority_rule_games',
    label: 'Checkers — majority rule',
    description: 'Games with a forced five-piece majority capture (10x10).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'took a five-piece majority capture in at least {n} game{s}',
  },
  {
    key: 'checkers_seed_master_games',
    label: 'Checkers — seed master',
    description: 'Games where you captured fifteen seeds (Nigeria).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'captured fifteen seeds in at least {n} game{s}',
  },
  {
    key: 'checkers_street_rules_wins',
    label: 'Checkers — street rules',
    description: 'Wins under Street Rules / huffing (Nigeria).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a Street Rules game at least {n} time{s}',
  },
  // ── Mahjong — from mahjong_player_state.game_counters at finish ───────────────────────────────────────────────
  {
    key: 'mahjong_discards',
    label: 'Mahjong — tiles discarded',
    description: 'Tiles discarded across your Mahjong hands.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'discarded at least {n} tile{s}',
  },
  {
    key: 'mahjong_chows_called',
    label: 'Mahjong — Chows called',
    description: 'Chows called from a discard.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'called at least {n} Chow{s}',
  },
  {
    key: 'mahjong_pungs_called',
    label: 'Mahjong — Pungs called',
    description: 'Pungs called from a discard.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'called at least {n} Pung{s}',
  },
  {
    key: 'mahjong_kongs_called',
    label: 'Mahjong — Kongs called',
    description: 'Kongs declared (concealed, added or from a discard).',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'declared at least {n} Kong{s}',
  },
  {
    key: 'mahjong_concealed_kongs',
    label: 'Mahjong — concealed Kongs',
    description: 'Concealed Kongs declared.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'declared at least {n} concealed Kong{s}',
  },
  {
    key: 'mahjong_added_kongs',
    label: 'Mahjong — added Kongs',
    description: 'Pungs upgraded to a Kong.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'upgraded at least {n} Pung{s} to a Kong',
  },
  {
    key: 'mahjong_hands_as_east',
    label: 'Mahjong — hands as East',
    description: 'Hands played seated as East.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} hand{s} as East',
  },
  {
    key: 'mahjong_exhaustive_draws_seen',
    label: 'Mahjong — walls watched',
    description: 'Hands played to an exhaustive wall draw.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played at least {n} hand{s} to the wall',
  },
  {
    key: 'mahjong_hands_won',
    label: 'Mahjong — hands won',
    description: 'Individual hands won.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} hand{s}',
  },
  {
    key: 'mahjong_seven_pairs_wins',
    label: 'Mahjong — seven pairs',
    description: 'Hands won with a seven-pairs hand.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} seven-pairs hand{s}',
  },
  {
    key: 'mahjong_thirteen_orphans_wins',
    label: 'Mahjong — thirteen orphans',
    description: 'Hands won with a thirteen-orphans hand.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} thirteen-orphans hand{s}',
  },
  {
    key: 'mahjong_self_draw_wins',
    label: 'Mahjong — self draw',
    description: 'Hands won on a self-drawn tile.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} hand{s} by self-draw',
  },
  {
    key: 'mahjong_concealed_wins',
    label: 'Mahjong — concealed win',
    description: 'Hands won fully concealed.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} concealed hand{s}',
  },
  {
    key: 'mahjong_no_call_wins',
    label: 'Mahjong — clean hand',
    description: 'Hands won without calling from a discard.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} hand{s} without a call',
  },
  {
    key: 'mahjong_won_fate_round',
    label: 'Mahjong — Simple win',
    description: 'Hands won under Simple (Fate Round) rules.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} Simple hand{s}',
  },
  {
    key: 'mahjong_won_hong_kong',
    label: 'Mahjong — Hong Kong win',
    description: 'Hands won under Hong Kong rules.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} Hong Kong hand{s}',
  },
  {
    key: 'mahjong_won_riichi',
    label: 'Mahjong — Riichi win',
    description: 'Hands won under Riichi rules.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} Riichi hand{s}',
  },
  {
    key: 'mahjong_won_mcr',
    label: 'Mahjong — MCR win',
    description: 'Hands won under MCR rules.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won at least {n} MCR hand{s}',
  },
  {
    key: 'mahjong_triple_meld',
    label: 'Mahjong — triple meld',
    description: 'Hands won with three or more exposed melds.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a three-meld hand at least {n} time{s}',
  },
  {
    key: 'mahjong_four_melds',
    label: 'Mahjong — four melds',
    description: 'Hands won with four exposed melds and a pair.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a four-meld hand at least {n} time{s}',
  },
  {
    key: 'mahjong_double_kong',
    label: 'Mahjong — double Kong',
    description: 'Hands won holding two or more Kongs.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won holding two Kongs at least {n} time{s}',
  },
  {
    key: 'mahjong_grand_slam',
    label: 'Mahjong — grand slam',
    description: 'Fully concealed four-meld hands won.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a fully concealed four-meld hand at least {n} time{s}',
  },
  {
    key: 'mahjong_quick_hand',
    label: 'Mahjong — quick hand',
    description: 'Hands won with ten or fewer discards.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a quick hand at least {n} time{s}',
  },
  {
    key: 'mahjong_high_fan',
    label: 'Mahjong — high fan',
    description: 'Hands won scoring high on the fan summary.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a high-fan hand at least {n} time{s}',
  },
  {
    key: 'mahjong_heavenly_hand',
    label: 'Mahjong — heavenly hand',
    description: 'Riichi hands won on the opening draw as East.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'won a heavenly hand at least {n} time{s}',
  },
  {
    key: 'mahjong_all_seats',
    label: 'Mahjong — full circle',
    description: 'Games where you played from all four seat positions.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'played all four seats in at least {n} game{s}',
  },
  {
    key: 'mahjong_table_sweep',
    label: 'Mahjong — table sweep',
    description: 'Games with three consecutive hand wins.',
    scope: 'per-game',
    availability: 'partial',
    phrase: 'swept three hands running in at least {n} game{s}',
  },
] as const

/**
 * Set-valued measures, addressable by `{ type: 'distinct', key: <key> }`. Backed by
 * `player_distinct`, where the primary key does the deduping and `count(*)` is the value.
 */
export const DISTINCT_SETS: readonly DistinctDef[] = [
  {
    key: 'modes_played',
    label: 'Game modes played',
    description: 'How many different game types this profile has finished.',
    availability: 'universal',
    phrase: 'played at least {n} different game mode{s}',
  },
  {
    key: 'opponents',
    label: 'Opponents faced',
    description: 'Distinct other profiles seated in the same finished game.',
    availability: 'partial',
    phrase: 'faced at least {n} different opponent{s}',
  },
  {
    // Emitted by mafiaFacts as `distinct:mafia_winning_roles:<role>` on a win, folded into
    // `player_distinct` by the award pass (see the `distinct:` convention in award.ts). This is
    // the one Mafia achievement that is genuinely a SET rather than a sum — "won as N different
    // roles" — which no summable counter can express.
    key: 'mafia_winning_roles',
    label: 'Mafia — roles won as',
    description: 'Distinct Mafia roles this profile has won a game as.',
    availability: 'partial',
    phrase: 'won as at least {n} different role{s}',
  },
  {
    key: 'rooms',
    label: 'Rooms played in',
    description: 'Distinct game rooms this profile has finished a game in.',
    availability: 'planned',
    phrase: 'played in at least {n} different room{s}',
  },
] as const

const COUNTER_KEYS = new Set(COUNTERS.map((c) => c.key))
const DISTINCT_KEYS = new Set(DISTINCT_SETS.map((d) => d.key))

/** True when a counter key is one the engine knows how to emit or plans to. */
export function isKnownCounter(key: string): boolean {
  return COUNTER_KEYS.has(key)
}

export function isKnownDistinctSet(key: string): boolean {
  return DISTINCT_KEYS.has(key)
}

/**
 * Counters and sets that will actually fire today.
 *
 * The admin UI should offer these first and mark the rest, because a rule referencing a
 * `planned` measure is indistinguishable at runtime from a typo: both read as zero, both
 * produce a trophy nobody can ever earn, and neither raises an error anywhere.
 */
export function liveCounters(): CounterDef[] {
  return COUNTERS.filter((c) => c.availability !== 'planned')
}

export function liveDistinctSets(): DistinctDef[] {
  return DISTINCT_SETS.filter((d) => d.availability !== 'planned')
}
