-- Security audit, systemic fix — stop new objects from being writable by default.
--
-- Findings C1 (tournaments), C2 (public_profiles) and H1 (quiplash / quick-draw-guess /
-- memory-match / ping-pong) all have the same root cause, not four separate mistakes:
-- Supabase ships `alter default privileges in schema public grant all on tables to anon,
-- authenticated`, so EVERY new table and view starts out writable by the public roles, and
-- the RLS-hardening programme in docs/rls-hardening.md was run as a per-object checklist.
-- Anything created after the checklist was written started open again — and did, four times.
--
-- Closing each hole individually leaves the default in place, so the fifth game will repeat
-- it. This migration changes the default itself: new tables and views in `public` are
-- SELECT-only for anon/authenticated from here on. Writes must be granted deliberately —
-- which, under the Option A architecture in docs/rls-hardening.md, they never should be:
-- every write goes through a server route holding the service role.
--
-- This affects FUTURE objects only; it does not retroactively change existing grants.
-- The three lockdown migrations shipped alongside it (20260803120000, 20260803130000,
-- 20260803140000) handle the existing ones.
--
-- Default privileges are recorded per granting-role. Objects created by migrations run as
-- the migration role, so set it for both that role and postgres to cover either path.

do $$
declare
  grantor text;
begin
  foreach grantor in array array['postgres', 'supabase_admin'] loop
    if exists (select 1 from pg_roles where rolname = grantor) then
      execute format(
        'alter default privileges for role %I in schema public revoke insert, update, delete on tables from anon, authenticated',
        grantor
      );
      -- Keep SELECT: reads stay open by design (realtime subscriptions depend on it).
      execute format(
        'alter default privileges for role %I in schema public grant select on tables to anon, authenticated',
        grantor
      );
      -- The service role is the trusted write boundary and must keep everything.
      execute format(
        'alter default privileges for role %I in schema public grant all on tables to service_role',
        grantor
      );
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   alter default privileges in schema public grant all on tables to anon, authenticated;
-- ----------------------------------------------------------------------------
