-- Per-game trophy accumulator for UNO (mirrors the Whot / Crazy Eights round-stats columns).
--
-- WHY A COLUMN AND NOT A DERIVATION. UNO is a POSITION game: the session holds only the top card,
-- piles and pending penalty, each hand holds only what a player holds RIGHT NOW, and a finished
-- hand is empty. Facts like "played a Skip", "called UNO", "caught someone who forgot to call",
-- "successfully challenged a Wild Draw Four", "changed the colour five times" or "won on a Wild"
-- do not survive to the end. The engine counts them as they happen — inside the hand write it
-- already does once it wins the turn's session CAS (see foldUnoPlay / foldUnoDraw / foldUnoChoose /
-- the challenge folds in src/lib/uno.ts) — and stashes them on this column.
-- `src/lib/trophies/game-facts/uno.ts` reads the bag back at finish.
--
-- GRANTS. `uno_player_hands` (20260719150000_uno.sql) carries table-level grants that auto-extend to
-- a new column, so no explicit `grant select (stats)` is needed — the same reasoning as the Whot and
-- Crazy Eights accumulators. The finish-time snapshot and the award pass both read it via the
-- service role, which bypasses grants/RLS regardless. (If that table ever migrates to column-level
-- grants, add `grant select (stats) on uno_player_hands to anon, authenticated;`.)
--
-- RESET. No explicit per-game reset: the accumulator lives on uno_player_hands, a fresh row per
-- (game_id, player_id), so each new game starts from the '{}' default; play-again clears the table.

alter table uno_player_hands
  add column if not exists stats jsonb not null default '{}'::jsonb;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   alter table uno_player_hands drop column if exists stats;
--
-- Dropping it retires the UNO per-game trophies to "never earned" (the facts builder reads an
-- absent bag as all-zero), which is the state before this migration.
-- ----------------------------------------------------------------------------
