-- Describe It — the secret word was public (same class as the Codewords key card, audit H2).
--
-- `describe_it_sessions.current_word` is the word the describer must get their team to say.
-- It was listed in DESCRIBE_IT_SESSION_SELECT and read from the browser with the publishable
-- anon key, so EVERY guesser's client already held the answer. The UI merely *rendered* it
-- conditionally (`isDescriber` in DescribeItPlay.tsx), which is presentation, not a control:
-- any guesser could read their own network response in devtools and win every turn.
--
-- `used_words` IS A SHADOW COPY OF THE SAME SECRET and is revoked with it. Every write that
-- sets `current_word` also appends that word to `used_words` (buildTurn, plus the guess and
-- skip paths in src/lib/describe-it.ts), so `used_words[last]` IS the current word. Revoking
-- only `current_word` would have moved the leak, not closed it — a guesser would just read the
-- last element instead. The clients' one legitimate use of the array was its LENGTH, as a
-- per-word counter: the word rotates on a correct guess and on a skip *without* `turn_index`
-- changing, so the describer needs a public value that ticks once per word to know when to
-- refetch. `word_seq` below is exactly that counter, and a count reveals nothing.
--
-- Not affected, deliberately:
--   * `describe_it_words` is a post-hoc LOG — rows are inserted only AFTER a word is guessed
--     or skipped, so those words are already revealed to everyone.
--   * `current_clue`, `current_clues` are public by design. The clues ARE the game.
--   * `status_message` interpolates the word ("…'s word was \"X\"") and stays public — but ONLY
--     because it is written on the turn -> break transition, i.e. at reveal, when the word is no
--     longer secret. ⚠️ If that message is ever set earlier in the turn, it becomes a third path
--     to the answer and must be revoked alongside the two columns below.
--
-- Same shape as `games.host_token` (0122) and `codewords_boards.key` (20260803170000), so the
-- same fix: revoke the public roles' table-wide SELECT and re-grant every column except the
-- secret ones. The data stays exactly where it is — the service role bypasses column grants,
-- so src/lib/describe-it.ts (clue validation, guess matching, word rotation, turn summaries) and
-- every describe-it write route keep working unchanged. No data movement, no server rewrite.
--
-- The describer gets their word back through POST /api/describe-it/my-word, which resolves the
-- caller from their secret resume token (or the host token, for a host who is seated as a
-- player) and returns the word only when that resolves to `describer_player_id`.
--
-- Realtime: anon `postgres_changes` payloads exclude columns the role cannot select, so
-- `current_word` stops arriving over realtime too. Safe here — the describe-it views use the
-- session event as a RELOAD TRIGGER (useGameTableSync -> load()), never as state to apply, and
-- the describer refetches the word through the route on every session change.
--
-- ⚠️ FUTURE SCHEMA CHANGES: anon/authenticated now hold COLUMN-level (not table-level) SELECT
-- on `describe_it_sessions`. A NEW column must also be granted (re-running this block does
-- that), or client reads of it will error. Fails closed — a read error, never a word leak.

do $$
declare
  session_cols text;
  role_name text;
begin
  -- Skip rather than abort where the table hasn't been created yet (a fresh environment
  -- applying migrations out of order), matching 20260803170000's guard.
  if not exists (
    select 1 from information_schema.tables
     where table_schema = 'public' and table_name = 'describe_it_sessions'
  ) then
    raise notice 'describe_it_sessions not present — skipping';
    return;
  end if;

  -- Public per-word counter that replaces the clients' only legitimate use of `used_words`.
  execute 'alter table public.describe_it_sessions
             add column if not exists word_seq integer
             generated always as (cardinality(used_words)) stored';

  select string_agg(quote_ident(column_name), ', ')
    into session_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'describe_it_sessions'
     and column_name not in ('current_word', 'used_words');

  foreach role_name in array array['anon', 'authenticated'] loop
    execute format('revoke select on public.describe_it_sessions from %I', role_name);
    execute format('grant select (%s) on public.describe_it_sessions to %I', session_cols, role_name);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   grant select on public.describe_it_sessions to anon, authenticated;
-- ----------------------------------------------------------------------------
