-- Security audit C2 — `public_profiles` re-opened the write path that `profiles` closes.
--
-- 20260803000000_profiles_identity.sql added `public_profiles` as a narrow read view for
-- leaderboards. Its comment reasons carefully about READS (columns enumerated explicitly so
-- a sensitive column can't leak later) and that reasoning is correct — but it never
-- considered writes:
--
--   * a view of the form `select <cols> from <table>` is AUTO-UPDATABLE in Postgres;
--   * Supabase's default privileges grant ALL on new objects in `public` to anon/authenticated,
--     so the view inherited INSERT/UPDATE/DELETE;
--   * a view without `security_invoker` runs with the DEFINER's rights, so the underlying
--     table's RLS never applies.
--
-- Verified against the live dev project: a direct anon UPDATE of `profiles` was correctly
-- refused (0 rows), and the identical UPDATE through `public_profiles` succeeded and wrote
-- through — an anonymous caller set another account's `trophy_level` to 999. Since trophies
-- and streaks underpin the paid tiers in docs/platform-features-master-plan.md, this is an
-- entitlement bypass, not just a cosmetic one.
--
-- Two independent fixes, because either alone is one mistake away from re-opening:
--   1. revoke the write privileges the view should never have had;
--   2. make the view run with the CALLER's rights, so `profiles`' own RLS applies to
--      anything that reaches it.

revoke insert, update, delete on public.public_profiles from anon, authenticated;

-- security_invoker makes the view honour the querying role's permissions and the
-- underlying table's RLS. `profiles_select_own` would then hide other people's rows, which
-- would break the leaderboards this view exists for — so pair it with an explicit
-- policy that exposes exactly the columns the view already selects, and nothing else.
alter view public.public_profiles set (security_invoker = on);

drop policy if exists "profiles_select_public_fields" on profiles;
create policy "profiles_select_public_fields" on profiles
  for select to anon, authenticated using (true);

-- The policy above admits the ROW; column-level grants decide which columns come with it.
-- profiles is owner-read for everything else, so grant only the four public fields.
-- ⚠️ FUTURE SCHEMA CHANGES: a new column on `profiles` is NOT readable by the public roles
-- unless it is added here deliberately. That is the intended default — fail closed.
revoke select on public.profiles from anon, authenticated;
grant select (id, handle, avatar_url, trophy_level, current_streak) on public.profiles to anon, authenticated;

grant all on public.profiles to service_role;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   alter view public.public_profiles set (security_invoker = off);
--   drop policy if exists "profiles_select_public_fields" on profiles;
--   grant select on public.profiles to anon, authenticated;
--   grant insert, update, delete on public.public_profiles to anon, authenticated;
-- ----------------------------------------------------------------------------
