-- Trophies unlocked DURING a round, before anyone knows whose profile they belong to.
--
-- THE CONSTRAINT THIS SOLVES. A gameplay route knows the PLAYER (it authenticates by
-- `resume_token` → `players.id`) and never the PROFILE — `players.profile_id` stays null until
-- the client posts attribution after the finished screen. `player_trophies` is keyed by profile,
-- so a route cannot write there. That is the entire reason nothing could pop mid-game.
--
-- So an unlock is recorded against the PLAYER here, immediately, and folded into the profile at
-- finish by the normal award pass. Two consequences worth stating:
--   * The toast can fire the instant it happens, from this row over realtime.
--   * A guest who never signs in still gets the toast; the row is simply never folded anywhere.
--     That is correct — they saw the moment, and the platform promises nothing more to a guest.
--
-- SERVER-WRITTEN ONLY. The unlock must come from state the server computed inside the action
-- handler. A client saying "I got it" is a free trophy for anyone with devtools, which is why
-- there are no anon/authenticated grants below — the same deny-all shape as the other trophy
-- tables.
--
-- Keyed by (game_id, player_id, trophy_id): one unlock per trophy per player per room. It is
-- deliberately NOT keyed by round — re-unlocking the same trophy in round two is not a second
-- award (`player_trophies` is unique per profile anyway), and this way the insert is a cheap
-- idempotent upsert rather than something the route has to reason about.

create table if not exists round_unlocks (
  game_id     text not null,
  player_id   uuid not null references players(id) on delete cascade,
  trophy_id   text not null references trophies(id) on delete restrict,
  unlocked_at timestamptz not null default now(),
  primary key (game_id, player_id, trophy_id)
);

-- The award pass reads one player's unlocks at finish; realtime reads by game.
create index if not exists idx_round_unlocks_game on round_unlocks (game_id);

-- ---------------------------------------------------------------------------
-- Lock it down: RLS with no policies (deny-all for anything that is not the
-- service role, which bypasses RLS by design) AND explicit revokes, same file.
-- ---------------------------------------------------------------------------
alter table round_unlocks enable row level security;

revoke all on table round_unlocks from public;
revoke all on table round_unlocks from anon;
revoke all on table round_unlocks from authenticated;
grant all on table round_unlocks to service_role;

-- Realtime carries the unlock to the player's own screen. The payload is a trophy id and a
-- player id — no profile, no identity, nothing that isn't already visible in the room. The table
-- stays unreadable by anon/authenticated above, so a client cannot enumerate it; it only ever
-- receives the change events for the game it is subscribed to.
do $$ begin
  alter publication supabase_realtime add table round_unlocks;
exception when duplicate_object then null;
end $$;

comment on table round_unlocks is
  'Trophies unlocked mid-round, recorded against the PLAYER because no profile exists during play. Folded into player_trophies at finish.';

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   drop table if exists round_unlocks;
--
-- Only alongside removing the instant-unlock call sites — otherwise the routes write to a table
-- that no longer exists and the insert failures are swallowed, silently losing the toasts.
-- ----------------------------------------------------------------------------
