-- Lock down `profile_merges` to match its sibling identity/trophy tables.
--
-- Security review 2026-08 (docs/security-audit-2026-08-pr748.md, finding F1). `profile_merges` was
-- created in 20260803000000_profiles_identity.sql with row-level security ENABLED and NO policies —
-- so anon/authenticated read zero rows and cannot INSERT/UPDATE/DELETE. But it was created BEFORE
-- the default-privileges lockdown (20260803160000) and was NOT included in the explicit-revoke loop
-- that 20260804000000_trophies_streaks.sql ran over the other service-role-only tables. It therefore
-- kept Supabase's default `grant all ... to anon, authenticated`.
--
-- Behavioural proof at the time of the review: anon `select from profile_merges` returned `200 []`
-- (a grant is present; RLS filters the rows), whereas every locked-down sibling returned
-- `42501 permission denied` (no grant at all).
--
-- WHY THIS MATTERS DESPITE RLS. RLS is the only control currently standing on this table, and RLS
-- does not cover everything: **TRUNCATE is not subject to row-level security**. With the residual
-- default grant, an anonymous caller can TRUNCATE this table. It is empty today (Case-B merges are
-- still a no-op), so the impact is currently nil — but this is the merge AUDIT LOG, and once the
-- account-merge batch starts writing to it, that residual grant becomes "anyone can erase the merge
-- history". This is the exact operation, and the exact reasoning, that made the sibling migration
-- revoke TRUNCATE explicitly. `profile_merges` was simply missed.
--
-- This migration adds the SECOND control the siblings already have ("no grant" is a stronger
-- statement than "a policy denies it") without changing behaviour for anyone: nothing but the
-- service role has ever read or written this table.

do $$
begin
  -- Already enabled in 20260803000000; assert it so this file is correct even if replayed
  -- somewhere that migration did not run.
  execute 'alter table public.profile_merges enable row level security';

  -- Privileges in Postgres are CUMULATIVE across the role, PUBLIC, and inheritance — so revoke
  -- from PUBLIC too, not just anon/authenticated, or a PUBLIC grant would still reach them.
  execute 'revoke all on public.profile_merges from anon, authenticated';
  execute 'revoke all on public.profile_merges from public';

  -- TRUNCATE is NOT subject to RLS (the whole point of this migration); TRIGGER and REFERENCES are
  -- likewise never issued by the data API. Default grants hand out all three.
  execute 'revoke truncate, trigger, references on public.profile_merges from anon, authenticated';

  -- The service role owns every read and write to this audit log, exactly as before.
  execute 'grant all on public.profile_merges to service_role';
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped. Restoring the default grant re-opens the TRUNCATE hole,
-- so only do this alongside a deliberate decision to make the table client-visible.
--
--   grant select, insert, update, delete on public.profile_merges to anon, authenticated;
-- ----------------------------------------------------------------------------
