-- Phase 6 RLS lockdown: tables added AFTER the Phase-5 sweep (migrations 0106–0126)
-- that regressed to permissive `FOR ALL USING(true) WITH CHECK(true)`, leaving them
-- directly writable/deletable by anyone with the public anon key.
--
-- Every writer for these tables is server-side (service-role client) with host/player
-- token authorization — verified there are no browser-client inserts/updates/deletes
-- to any of them. So we lock anon to SELECT-only, exactly like the Phase-5 core sweep
-- (20260628132823). Anon SELECT stays open for the public lobby + realtime read
-- subscriptions; the service role bypasses RLS so server writes keep working.
--
-- Covers: quiplash*, quick_draw* (incl. the guess sub-mode), memory_match*,
-- ping_pong_sessions, and the tournament tables (which additionally had a plaintext
-- host_token readable by anon — revoked below).

do $$
declare
  tbl text;
  pol record;
  tables text[] := array[
    'quiplash_sessions', 'quiplash_answers', 'quiplash_battles', 'quiplash_votes',
    'quick_draw_sessions', 'quick_draw_assignments', 'quick_draw_drawings',
    'quick_draw_titles', 'quick_draw_votes',
    'quick_draw_guess_sessions', 'quick_draw_guess_players', 'quick_draw_guess_words',
    'quick_draw_guess_guesses',
    'memory_match_progress', 'memory_match_submissions',
    'ping_pong_sessions',
    'tournaments', 'tournament_players', 'tournament_games',
    'anonymous_messages', 'anonymous_room_bans'
  ];
begin
  foreach tbl in array tables loop
    if to_regclass('public.' || tbl) is not null then
      execute format('alter table public.%I enable row level security', tbl);
      for pol in select policyname from pg_policies where schemaname = 'public' and tablename = tbl loop
        execute format('drop policy %I on public.%I', pol.policyname, tbl);
      end loop;
      execute format('create policy %I on public.%I for select using (true)', tbl || '_read', tbl);
    end if;
  end loop;
end $$;

-- tournaments.host_token is the tournament's secret credential but lived on an
-- anon-readable table (the 0122 column-revoke only covered games/players). Revoke
-- table-wide SELECT and re-grant every column EXCEPT host_token, so anon can still
-- read tournament state for the lobby but never the token. Fails closed: a future
-- column added to `tournaments` must be re-granted (re-run this block), which errors
-- a read rather than leaking the token.
do $$
declare
  cols text;
  role_name text;
begin
  if to_regclass('public.tournaments') is not null then
    select string_agg(quote_ident(column_name), ', ')
      into cols
      from information_schema.columns
     where table_schema = 'public' and table_name = 'tournaments' and column_name <> 'host_token';

    foreach role_name in array array['anon', 'authenticated'] loop
      execute format('revoke select on public.tournaments from %I', role_name);
      execute format('grant select (%s) on public.tournaments to %I', cols, role_name);
    end loop;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   grant select on public.tournaments to anon, authenticated;
--   -- and, per table, restore: create policy <tbl>_all on public.<tbl> for all using (true) with check (true);
-- ----------------------------------------------------------------------------
