-- Phase 2 hardening: end the TOCTOU class of bugs for the first-mode
-- bonus (docs/coins-and-shop-plan.md §"Earning" — "First-time-playing-a-mode
-- bonus").
--
-- The award pass currently does a `SELECT` of `coin_ledger` before calling
-- `award_coins()` — two near-simultaneous finishes of the same mode (a
-- retry racing the first request, two tabs in a bracket, a resume that
-- re-hits the finish path) can both pass the SELECT and both credit
-- +50 coins. The RPC has no idea a per-mode uniqueness rule exists.
--
-- Same shape as the existing `uq_coin_ledger_one_shot_grant` (one-shot per
-- profile for launch_grant_v1 / welcome_v1) — extend it to first_mode_bonus,
-- keyed on (profile_id, ref_id) because the "one-shot" scope is per game
-- TYPE, and the writer stamps `ref_id = 'first_mode:{game_type}'`.
--
-- On duplicate the RPC raises unique_violation and the award-service catches
-- it as "already awarded" — no coin is credited twice, no matter how many
-- concurrent passes pass their pre-check.

create unique index if not exists uq_coin_ledger_first_mode_bonus
  on coin_ledger (profile_id, ref_id)
  where reason = 'first_mode_bonus';

-- ---------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   drop index if exists uq_coin_ledger_first_mode_bonus;
-- ---------------------------------------------------------------------------
