-- Security hardening: lock down SECURITY DEFINER / privileged RPCs that were left
-- with the default PUBLIC EXECUTE grant.
--
-- Postgres grants EXECUTE to PUBLIC on every new function by default. Several game
-- RPCs never revoked it, so any browser holding the public anon key could call them
-- directly and bypass all the authorization that lives in the server route:
--   * word_rush_add_score      — arbitrary score writes for any player (no token check)
--   * codewords_process_guess  — drive guess resolution / force a winner (no token check)
--   * restart_tournament       — wipe a finished tournament's history + reset standings
--   * rotate_player_resume_token — INVOKER, but the PUBLIC grant was never revoked
--
-- Every legitimate caller invokes these through the service-role client
-- (getSupabaseAdmin), which is NOT subject to these grants. The tournament restart
-- route was switched from the anon client to the admin client in the same change set
-- so this revoke does not break it.
--
-- Implemented defensively with to_regprocedure() so a signature/existence mismatch
-- on any one function is skipped rather than failing the whole migrate job.

do $$
declare
  fn text;
  fns text[] := array[
    'public.word_rush_add_score(text, uuid, integer)',
    'public.codewords_process_guess(uuid, integer, text)',
    'public.restart_tournament(text)',
    'public.rotate_player_resume_token(text, text)'
  ];
begin
  foreach fn in array fns loop
    if to_regprocedure(fn) is not null then
      execute format('revoke execute on function %s from public', fn);
      execute format('revoke execute on function %s from anon', fn);
      execute format('revoke execute on function %s from authenticated', fn);
      execute format('grant execute on function %s to service_role', fn);
    end if;
  end loop;
end $$;

-- codewords_process_guess was additionally the only definer function in the repo with
-- an unpinned search_path (a definer-hijack vector + Supabase linter finding). Pin it
-- without rewriting the body.
do $$
begin
  if to_regprocedure('public.codewords_process_guess(uuid, integer, text)') is not null then
    execute 'alter function public.codewords_process_guess(uuid, integer, text) set search_path = public, pg_temp';
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted — restores the permissive PUBLIC execute). Apply as a NEW forward
-- migration; do NOT edit this file after it has shipped.
--   grant execute on function public.word_rush_add_score(text, uuid, integer) to public;
--   grant execute on function public.codewords_process_guess(uuid, integer, text) to public;
--   grant execute on function public.restart_tournament(text) to public;
--   grant execute on function public.rotate_player_resume_token(text, text) to public;
-- ----------------------------------------------------------------------------
