-- Whot: hide the ordered deck from the publishable anon key.
--
-- Whot's per-player hand redaction (`/api/whot/hands` + `whot_player_hands.cards`) is the template
-- the other card games copy, but it buys very little while `whot_sessions.draw_pile` still ships
-- the FULL ORDERED DECK to every client holding the publishable anon key:
--
--   * In a 2-player game, `draw_pile` + `discard_pile` + your own hand subtract from the known
--     54-card Nigerian Whot deck to give your opponent's EXACT hand.
--   * In an N-player game you still know every future draw, IN ORDER — including exactly which
--     card the Pick Two / Pick Five / General Market penalty is about to hand each opponent.
--
-- Both piles are therefore revoked with the same do-block used for `crazy_eights_sessions`
-- (20260815120000), `codewords_boards.key` (20260803170000) and `games.host_token` (0122).
--
-- Nothing client-side loses information it legitimately had: every browser/mobile reader used
-- only `.length` of these arrays (`WhotBoard.tsx`, `WhotPlayerView.tsx`, `WhotHostView.tsx`,
-- `isDrawPileDepleted`), and the face-up card is a separate `top_card` column that stays public —
-- it is public information at the table anyway. Generated `draw_count` / `discard_count` replace
-- the two legitimate uses: a SIZE reveals neither the ORDER nor the IDENTITY of the cards, which
-- is the actual secret.
--
-- Server-side play (src/lib/whot.ts, src/lib/whot-bot-driver.ts, src/lib/push.ts) reads and
-- rewrites the piles through the service role, which is unaffected by a column revoke.
--
-- MIGRATION NAME. Deliberately timestamped AFTER every existing migration. The grant below is a
-- SNAPSHOT of the column list at the time it runs, so on a fresh database it must run after the
-- last migration that adds a column to `whot_sessions` (20260926120000_whot_reshuffle_count.sql);
-- an earlier name would leave `reshuffle_count` ungranted and 42501 the client's whole select.
--
-- ⚠️ FUTURE SCHEMA CHANGES: anon/authenticated now hold COLUMN-level (not table-level) SELECT on
-- `whot_sessions`. A NEW column must also be granted (re-running the do-block below does that),
-- or client reads of it will error. Fails closed — a read error, never a deck leak.

do $$
declare
  session_cols text;
  role_name text;
begin
  -- Skip rather than abort where the table hasn't been created yet (a fresh environment applying
  -- migrations out of order), matching 20260803170000's guard.
  if not exists (
    select 1 from information_schema.tables
     where table_schema = 'public' and table_name = 'whot_sessions'
  ) then
    raise notice 'whot_sessions not present — skipping';
    return;
  end if;

  -- Public pile sizes. Stored + generated, so they can never drift from the piles they count and
  -- no application code has to maintain them. These columns are jsonb (NOT postgres arrays), so
  -- this is jsonb_array_length, not cardinality. Both it and jsonb_typeof are immutable, which is
  -- what a generated column requires. The typeof guard keeps the count 0 rather than erroring on
  -- a null pile or a non-array value.
  alter table public.whot_sessions
    add column if not exists draw_count integer
    generated always as (
      case when jsonb_typeof(draw_pile) = 'array' then jsonb_array_length(draw_pile) else 0 end
    ) stored;

  alter table public.whot_sessions
    add column if not exists discard_count integer
    generated always as (
      case when jsonb_typeof(discard_pile) = 'array' then jsonb_array_length(discard_pile) else 0 end
    ) stored;

  select string_agg(quote_ident(column_name), ', ')
    into session_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'whot_sessions'
     and column_name not in ('draw_pile', 'discard_pile');

  foreach role_name in array array['anon', 'authenticated'] loop
    execute format('revoke select on public.whot_sessions from %I', role_name);
    execute format('grant select (%s) on public.whot_sessions to %I', session_cols, role_name);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped. Re-exposes the ordered deck, so only as an incident lever:
--
--   grant select on public.whot_sessions to anon, authenticated;
--   alter table public.whot_sessions drop column if exists draw_count;
--   alter table public.whot_sessions drop column if exists discard_count;
--
-- Note the table-level grant supersedes the column grants; dropping the counts requires the
-- clients to have been rolled back to reading the piles first.
-- ----------------------------------------------------------------------------
