-- Security audit C1 — tournaments were never covered by the Phase 4 RLS lockdown.
--
-- `0097_tournaments.sql` created the three tournament tables with
-- `FOR ALL USING (true) WITH CHECK (true)`, and the lockdown programme
-- (migrations 0106-0121) covered the 16 *game* table groups but not tournaments.
-- Verified against the live dev project: with only the publishable anon key an
-- attacker could read `tournaments.host_token` for every tournament and PATCH any
-- `tournament_players` row (confirmed by executing both). That is full tournament
-- takeover plus arbitrary score rewriting.
--
-- Two separate holes, so two separate fixes:
--   1. WRITE — replace the permissive policies with SELECT-only `_read` policies and
--      revoke INSERT/UPDATE/DELETE from the public roles (mirrors 0106-0121).
--   2. READ  — `host_token` is the host credential sitting in a broadly-readable row.
--      Row-level access grants every column, so hiding it needs COLUMN-level grants,
--      the same treatment `games.host_token` got in 0122.
--
-- Writes continue to work because every tournament write path is either the service
-- role (which bypasses both) or a `security definer` RPC (`join_tournament`,
-- `leave_tournament`, `restart_tournament`), which runs as its owner.

-- ---------------------------------------------------------------------------
-- 1. Write lockdown
-- ---------------------------------------------------------------------------
drop policy if exists "tournaments_all" on tournaments;
drop policy if exists "tournament_players_all" on tournament_players;
drop policy if exists "tournament_games_all" on tournament_games;

drop policy if exists "tournaments_read" on tournaments;
drop policy if exists "tournament_players_read" on tournament_players;
drop policy if exists "tournament_games_read" on tournament_games;

create policy "tournaments_read" on tournaments for select using (true);
create policy "tournament_players_read" on tournament_players for select using (true);
create policy "tournament_games_read" on tournament_games for select using (true);

revoke insert, update, delete on public.tournaments from anon, authenticated;
revoke insert, update, delete on public.tournament_players from anon, authenticated;
revoke insert, update, delete on public.tournament_games from anon, authenticated;

grant all on public.tournaments to service_role;
grant all on public.tournament_players to service_role;
grant all on public.tournament_games to service_role;

-- ---------------------------------------------------------------------------
-- 2. Hide the host credential from the public roles (0122 pattern)
-- ---------------------------------------------------------------------------
-- ⚠️ FUTURE SCHEMA CHANGES: anon/authenticated now hold COLUMN-level (not table-level)
-- SELECT on `tournaments`. Any NEW column must also be granted (re-running this block
-- does that) or client reads of it will error. Fails closed — a read error, never a
-- token leak.
do $$
declare
  tournament_cols text;
  role_name text;
begin
  select string_agg(quote_ident(column_name), ', ')
    into tournament_cols
    from information_schema.columns
   where table_schema = 'public' and table_name = 'tournaments' and column_name <> 'host_token';

  foreach role_name in array array['anon', 'authenticated'] loop
    execute format('revoke select on public.tournaments from %I', role_name);
    execute format('grant select (%s) on public.tournaments to %I', tournament_cols, role_name);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   grant select on public.tournaments to anon, authenticated;
--   grant insert, update, delete on public.tournaments to anon, authenticated;
--   grant insert, update, delete on public.tournament_players to anon, authenticated;
--   grant insert, update, delete on public.tournament_games to anon, authenticated;
--   drop policy if exists "tournaments_read" on tournaments;
--   drop policy if exists "tournament_players_read" on tournament_players;
--   drop policy if exists "tournament_games_read" on tournament_games;
--   create policy "tournaments_all" on tournaments for all using (true) with check (true);
--   create policy "tournament_players_all" on tournament_players for all using (true) with check (true);
--   create policy "tournament_games_all" on tournament_games for all using (true) with check (true);
-- ----------------------------------------------------------------------------
