-- Re-key awarded_sessions from the ROOM to the ROUND.
--
-- `awarded_sessions.session_id` held the bare game code. But "play again" UPDATEs the same
-- `games` row — same id, status back to `waiting` — so one code covers every round a room ever
-- plays. The claim is taken before awarding, so round one claimed the code and every round after
-- it hit the primary-key conflict and awarded NOTHING: no trophies, no `games_played`, no streak
-- day. A room that played all evening recorded a single game.
--
-- The key is now `<CODE>#<finished_at ISO>`, which separates rounds while still collapsing
-- retried attributions for the SAME round — the reason the claim exists.
--
-- WHY THIS BACKFILL MATTERS. Without it, every already-awarded round becomes claimable again
-- under the new key shape, and the next client to re-attribute an old finished game would award
-- its trophies a second time. Rewriting the existing rows to the new shape keeps them blocking.
--
-- The format must match JavaScript's `toISOString()` exactly (`roundKey` in
-- src/lib/trophies/award.ts) or the rewritten rows block nothing.

-- Guard against a primary-key collision. If the application deploys BEFORE this migration runs,
-- the new roundKey immediately starts writing `<CODE>#<finished_at>` rows. A profile that already
-- has such a row for a round would then collide when we try to rewrite its bare-code row to the
-- same key. Drop the now-redundant bare-code row first — the new-shape row already blocks that
-- round — so the UPDATE below can never hit a duplicate key.
delete from awarded_sessions a
 using games g
 where g.id = a.session_id
   and g.finished_at is not null
   and position('#' in a.session_id) = 0
   and exists (
     select 1
       from awarded_sessions b
      where b.profile_id = a.profile_id
        and b.session_id =
          a.session_id || '#' || to_char(g.finished_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
   );

update awarded_sessions a
   set session_id = a.session_id || '#' || to_char(g.finished_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  from games g
 where g.id = a.session_id
   and g.finished_at is not null
   -- Only rows still in the old bare-code shape. Safe to re-run.
   and position('#' in a.session_id) = 0;

-- Rows whose game has no `finished_at`, or whose game no longer exists, are deliberately left
-- alone: they keep blocking under the old shape, which is the conservative direction. The code
-- falls back to the bare code in exactly that case, so they still match.

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   update awarded_sessions
--      set session_id = split_part(session_id, '#', 1)
--    where position('#' in session_id) > 0;
--
-- Only meaningful alongside reverting `roundKey`, and note it would collapse several rounds of
-- one room onto a single key — which is the bug this migration exists to fix.
-- ----------------------------------------------------------------------------
