-- Ayo (Ayo Olopon) per-game trophy accumulator.
--
-- Traditional Ayo keeps a POSITION, not a record: `pits` is only where the seeds currently
-- sit, and `captured_a/b` / `houses_a/b` are running totals. The things trophies want to
-- reward happen DURING a move and leave no trace afterwards — which of your six houses you
-- sowed from, how far a relay lap travelled, whether every one of your moves captured, the
-- worst seed deficit you clawed back from. Relay sowing rewrites the board on every move, so
-- there is nothing to reconstruct these from at finish. This is that trace.
--
-- WHY PAIRED COLUMNS, NOT ONE PER PLAYER. Ayo stores its whole game on ONE `ayo_sessions`
-- row with `a_*` / `b_*` columns (`captured_a`, `a_time_ms`, `a_win_streak`, …); there is no
-- per-player table to hang a blob on. So the accumulator mirrors that layout exactly:
-- `a_stats` for the Player-A seat, `b_stats` for the Player-B seat. The facts builder
-- (src/lib/trophies/game-facts/ayo.ts) maps a_stats -> player_a_id and b_stats -> player_b_id
-- at finish.
--
-- PER-GAME STATE. `initializeAyoGame` overwrites the whole row on a rematch (resetting pits,
-- captures and houses); it now resets these blobs to '{}' too, so they only ever describe the
-- current game. The engine writes them INSIDE the same optimistic-concurrency window (CAS on
-- `updated_at`) that guards every board write (see persistSession in src/lib/ayo.ts) — only
-- the request that wins the CAS commits, so a move is never double-counted. Nothing about move
-- or capture legality changed; these writes are purely additive.
--
-- Shape (all keys optional, absent == 0):
--   moves            this seat's completed moves this game
--   capturing_moves  of those, how many captured a house (completed exactly four)
--   last_capture     0/1 — did this seat's MOST RECENT move capture (for the "final-move win")
--   sown_mask        bitmask of local houses (0–5) this seat has sowed from; 63 == all six
--   max_sown         most seeds moved in a single move, relay laps included (a full lap == 12)
--   worst_deficit    largest (opponent captured − this seat captured) seen after any move

alter table ayo_sessions
  add column if not exists a_stats jsonb not null default '{}'::jsonb,
  add column if not exists b_stats jsonb not null default '{}'::jsonb;

-- Belt-and-braces column SELECT for the realtime clients (which select every column). Server
-- reads/writes use the service role and bypass grants entirely; this only matters if the
-- table-level grant ayo_sessions currently relies on is ever tightened to column level.
grant select (a_stats, b_stats) on ayo_sessions to anon, authenticated;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   revoke select (a_stats, b_stats) on ayo_sessions from anon, authenticated;
--   alter table ayo_sessions drop column if exists a_stats, drop column if exists b_stats;
-- ----------------------------------------------------------------------------
