-- Lock tables that hold secret/server-only state to service-role-only access.
--
-- Two groups, both accessed exclusively by the server (service-role client) — verified
-- there are no browser-client reads/writes and no realtime (postgres_changes)
-- subscriptions on any of them:
--
--   * jikan_search_cache / jikan_anime_cache — RLS was NEVER enabled (created in
--     0001_base_schema). With Supabase's default anon grants they were fully anon
--     read/write/delete: cache poisoning (attacker-controlled anime titles/images
--     rendered into Who-Said-This) and unbounded storage growth. No app code references
--     these tables at all.
--   * mafia_player_states / mafia_sessions — leak every player's secret role and the
--     night-action targets; the mafia client reads game state via /api/mafia/[code]/state
--     (a redacted, service-role route), NOT these tables directly (see the explicit
--     comment in MafiaPlayerView.tsx that postgres_changes is not used here).
--   * mahjong_player_state (tiles) / landmine_round_mines (mine positions) — same shape:
--     hidden state served through API routes.
--
-- Enable RLS, drop every existing policy, and add NO policy → PostgREST denies anon
-- entirely while the service role continues to bypass RLS. Also drop each table from the
-- realtime publication defensively so no change payload can reach anon.

do $$
declare
  tbl text;
  pol record;
  tables text[] := array[
    'jikan_search_cache', 'jikan_anime_cache',
    'mafia_player_states', 'mafia_sessions',
    'mahjong_player_state', 'landmine_round_mines'
  ];
begin
  foreach tbl in array tables loop
    if to_regclass('public.' || tbl) is not null then
      execute format('alter table public.%I enable row level security', tbl);
      for pol in select policyname from pg_policies where schemaname = 'public' and tablename = tbl loop
        execute format('drop policy %I on public.%I', pol.policyname, tbl);
      end loop;
      -- Remove from realtime publication if present (ignore if it isn't).
      if exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = tbl
      ) then
        execute format('alter publication supabase_realtime drop table public.%I', tbl);
      end if;
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   per table: create policy <tbl>_all on public.<tbl> for all using (true) with check (true);
-- ----------------------------------------------------------------------------
