-- Phase 2 hardening: idempotency for the guest earning path
-- (docs/coins-and-shop-plan.md §"Guest earnings & migration").
--
-- Phase 1's `guest_pending_grants` had no uniqueness constraint. The Phase 2
-- server-side write in /api/profile/attribute is best-effort and the CLIENT
-- effect that triggers it can fire more than once for one finished round:
--
--   * React StrictMode double-mounts the finish screen in dev,
--   * A refresh on the finish screen re-runs the attribution effect,
--   * A resume back into an already-finished game re-hits the same state.
--
-- Without a constraint, each fire inserted another row, inflating the guest's
-- pending balance. The 500-coin cap in `migrate_guest_grants` hides the damage
-- at signup, but the results-screen CTA quotes the inflated number in the
-- meantime — a "Sign up to claim 480 coins" that becomes 240 after cap looks
-- broken to the player.
--
-- The natural key is (device_id, game_id, session_id, reason):
--   * device_id + game_id — same device, same room.
--   * session_id — REQUIRED. "Play again" reuses the games row (same code) for
--     a new round, and the trophy path already keys idempotency on
--     (game_id, finished_at) via `roundKey()`. The guest writer sets
--     session_id = finished_at so play-again's round 2 gets its own key.
--   * reason — win + first_mode_bonus coexist for the same round; splitting
--     them lets both be inserted, and each stays idempotent on repeat fires.
--
-- coalesce over a partial-index predicate: `session_id` can in principle
-- be null (legacy rows exist, and a legacy caller could still write null).
-- Postgres treats nulls as distinct in a unique index by default, which would
-- silently reopen the dup path. Use NULLS NOT DISTINCT (PG 15+) so a null
-- session_id key still deduplicates against another null.

create unique index if not exists uq_guest_pending_grants_round_reason
  on guest_pending_grants (device_id, game_id, session_id, reason)
  nulls not distinct
  where game_id is not null;

-- ---------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   drop index if exists uq_guest_pending_grants_round_reason;
-- ---------------------------------------------------------------------------
