-- Retire the cross-game trophies.
--
-- Trophies are strictly per game: the profile lists the games you have PLAYED and opens each
-- one's trophies. There is no screen a game-less trophy can appear on. The seed no longer builds
-- any and the admin form no longer lets you create one, but 13 rows predate that decision and
-- the seed is idempotent — it only inserts missing ids, so it never removed them.
--
-- Left alone they are worse than dead rows: the award pass selects every `is_active` trophy, so
-- players keep EARNING them. Points land on `profiles.trophy_points`, the level moves, and there
-- is nothing anywhere that explains why. Retiring them stops that at the source.
--
-- RETIRE, DO NOT DELETE. `player_trophies.trophy_id` is ON DELETE RESTRICT and some of these are
-- already earned. Anyone who has one keeps it and keeps its points — `recompute_profile_points`
-- joins `trophies` without filtering on `is_active` precisely so retiring a trophy never takes
-- points off someone who earned it fairly. This only stops NEW awards.

update trophies
   set is_active = false
 where game_type is null
   and is_active;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   update trophies set is_active = true where game_type is null;
--
-- Only meaningful alongside a UI that renders a cross-game bucket again — without one this
-- just resumes awarding trophies nobody can see.
-- ----------------------------------------------------------------------------
