-- Security audit H1 — the games that shipped after the Phase 4 lockdown programme.
--
-- Migrations 0106-0121 locked 16 game table groups. Quiplash (20260708210000), Quick Draw
-- guess mode (20260710150000), Memory Match (20260705120001) and Ping Pong (20260717120000)
-- all landed afterwards and were created with the old `FOR ALL USING (true) WITH CHECK (true)`
-- template, so they inherited the permissive default the programme was closing.
--
-- Verified against the live dev project: with only the publishable anon key, an UPDATE
-- against a REAL row in each of these tables returned 1 row (i.e. it took effect), and
-- DELETE was permitted too. Scores and round state in these four games were rewritable
-- mid-match by anyone.
--
-- This is the "same bug in sibling code" case: the lockdown was run as a per-game checklist,
-- so every game added after the checklist was written started open. 20260803160000 changes
-- the default so the next game cannot repeat it.
--
-- Safe to apply: every write path for these games already uses the service role
-- (all 17 route handlers under /api/{quiplash,quick-draw,matching-pairs,ping-pong}
-- call getSupabaseAdmin(), and no client-side code writes these tables).

do $$
declare
  tbl text;
  pol text;
  locked_tables text[] := array[
    'quiplash_sessions', 'quiplash_answers', 'quiplash_battles', 'quiplash_votes',
    'quick_draw_guess_sessions', 'quick_draw_guess_players', 'quick_draw_guess_words',
    'quick_draw_guess_guesses',
    'memory_match_progress', 'memory_match_submissions',
    'ping_pong_sessions',
    -- Found by the INSERT sweep in src/lib/rls-boundaries.integration.test.ts, not by the
    -- manual audit pass: UPDATE was already refused on these, but anon still held INSERT, so
    -- anyone could inject drawings, titles, votes and messages into a live game.
    'quick_draw_sessions', 'quick_draw_assignments', 'quick_draw_drawings',
    'quick_draw_titles', 'quick_draw_votes',
    'anonymous_messages', 'anonymous_room_bans'
  ];
begin
  foreach tbl in array locked_tables loop
    -- Skip anything not present in this environment rather than failing the whole migration.
    if not exists (
      select 1 from information_schema.tables
       where table_schema = 'public' and table_name = tbl
    ) then
      raise notice 'skipping %, not present', tbl;
      continue;
    end if;

    execute format('alter table public.%I enable row level security', tbl);

    -- Drop every existing policy by name from the catalog — the permissive policies were
    -- created under inconsistent names ("public_quiplash_votes", "ping_pong_sessions_policy",
    -- …), so enumerating them by hand would miss one.
    for pol in
      select policyname from pg_policies where schemaname = 'public' and tablename = tbl
    loop
      execute format('drop policy %I on public.%I', pol, tbl);
    end loop;

    -- Reads stay open: realtime subscriptions for these games depend on anon SELECT.
    execute format('create policy %I on public.%I for select using (true)', tbl || '_read', tbl);

    execute format('revoke insert, update, delete on public.%I from anon, authenticated', tbl);
    execute format('grant select on public.%I to anon, authenticated', tbl);
    execute format('grant all on public.%I to service_role', tbl);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped. Restores the permissive pre-audit state for all 18 tables:
--
--   do $$
--   declare tbl text;
--   begin
--     foreach tbl in array array['quiplash_sessions','quiplash_answers','quiplash_battles',
--       'quiplash_votes','quick_draw_guess_sessions','quick_draw_guess_players',
--       'quick_draw_guess_words','quick_draw_guess_guesses','memory_match_progress',
--       'memory_match_submissions','ping_pong_sessions','quick_draw_sessions',
--       'quick_draw_assignments','quick_draw_drawings','quick_draw_titles','quick_draw_votes',
--       'anonymous_messages','anonymous_room_bans'] loop
--       execute format('drop policy if exists %I on public.%I', tbl || '_read', tbl);
--       execute format('create policy %I on public.%I for all using (true) with check (true)', tbl || '_all', tbl);
--       execute format('grant insert, update, delete on public.%I to anon, authenticated', tbl);
--     end loop;
--   end $$;
-- ----------------------------------------------------------------------------
