-- Ludo per-game trophy accumulator.
--
-- Ludo keeps a POSITION, not a record: `ludo_player_state.pieces` is only the current
-- placement of a player's four pieces. Dice rolls, captures and safe landings leave no
-- trace once the turn is over, so a finish-time facts builder (unlike Chess's PGN replay
-- or Yahtzee's scorecard) has nothing to read them back from. This column is that trace:
-- a per-game scratch counter blob the engine bumps IN PLAY, folded into lifetime trophy
-- counters at finish by src/lib/trophies/game-facts/ludo.ts.
--
-- It lives on `ludo_player_state` (one row per player per game, dropped on play-again by
-- clearSessionTables), so `game_counters` is naturally per-GAME state — it resets with the
-- rest of the session. The engine writes it inside the same optimistic-concurrency (CAS)
-- window that guards piece writes (see persistMove / processLudoRoll in src/lib/ludo.ts):
-- only the request that wins the session CAS ever commits, so no double counting.
--
-- Shape (all optional, absent == 0): sixes_rolled, double_sixes, captures_made,
-- safe_landings, times_captured, pieces_deployed, rolls, max_captures_in_move,
-- captured_mask (bitmask of this player's own piece ids that were sent home),
-- cap_vs_red|green|yellow|blue (captures dealt to each colour), dsix_streak,
-- dsix_streak_max, and the 0/1 in-play flags full_deploy, shield, fast_start,
-- all_four_yarded.

alter table ludo_player_state
  add column if not exists game_counters jsonb not null default '{}'::jsonb;

-- Column-level SELECT, mirroring how a new column is handled elsewhere on the stack.
-- `ludo_player_state` currently holds a TABLE-level SELECT grant for anon/authenticated
-- (it predates the column-level lockdown that only reworked `games`/`players` in 0122),
-- so this grant is belt-and-braces: harmless where a table grant already covers it, and
-- the thing that keeps client reads (realtime subscriptions select every column) from a
-- 42501 if that table grant is ever tightened to column level. Server writes/reads use the
-- service role and bypass grants entirely.
grant select (game_counters) on ludo_player_state to anon, authenticated;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   revoke select (game_counters) on ludo_player_state from anon, authenticated;
--   alter table ludo_player_state drop column if exists game_counters;
-- ----------------------------------------------------------------------------
