-- Revoke the residual anon/authenticated WRITE grants on the session tables that carry the
-- per-game trophy accumulators. Defense-in-depth (security review 2026-08, finding F2).
--
-- THE GAP. These tables follow the gameplay convention "anon reads everything, the server writes
-- everything": a `for select using (true)` policy (or, for the hidden-hand table, no policy at all)
-- plus a table created back when Supabase's default `grant all to anon, authenticated` was in force.
-- The result is that anon holds INSERT/UPDATE/DELETE/TRUNCATE grants it should never have — the same
-- shape as finding F1 (`profile_merges`) and the trophy-table lockdown in 20260804000000.
--
-- IS ANYTHING EXPLOITABLE TODAY? No. Every anon write is already stopped by RLS — verified live
-- against a REAL `ayo_sessions` row (an anon same-value UPDATE changed 0 rows), and reads of the
-- hidden-state table return 0 rows to anon while the service role sees data. This migration adds the
-- SECOND control the trophy tables already have, so that RLS is not the *only* thing standing
-- between an anonymous client and the game state these rows hold (including the trophy accumulators
-- `a_stats`/`red_stats`/`stats`/`game_counters` that the per-game trophies are derived from).
--
-- WHY WRITES ONLY, NOT SELECT. The board-readable tables (`ayo_sessions`, `checkers*_sessions`,
-- `scrabble_player_state`) are read by anon over realtime — revoking SELECT would break the live
-- board. So only the write privileges are revoked here; the read path is left exactly as it is.
-- `mahjong_player_state` is a hidden-hand table whose reads are already denied by RLS (no policy);
-- its SELECT grant is inert and left untouched to keep this migration minimal and read-only-safe.
--
-- SCOPE. Deliberately limited to the tables this feature added trophy accumulators to. The same
-- residual-grant pattern exists platform-wide on other gameplay session tables and on the other
-- hidden-state tables (mafia_*, landmine_round_mines); that broader sweep is tracked separately —
-- it is not introduced by the trophy work and each table needs its own read-path check first.

do $$
declare
  t text;
begin
  foreach t in array array[
    'ayo_sessions',
    'checkers_sessions',
    'checkers10_sessions',
    'scrabble_player_state',
    'mahjong_player_state'
  ] loop
    if to_regclass('public.' || t) is not null then
      -- RLS is already enabled on all of these; assert it so this file is correct if replayed.
      execute format('alter table public.%I enable row level security', t);
      -- Revoke only the WRITE privileges — never SELECT (realtime needs it on the board tables).
      -- Privileges are cumulative across the role and PUBLIC, so revoke from PUBLIC too.
      execute format('revoke insert, update, delete, truncate, trigger, references on public.%I from anon, authenticated', t);
      execute format('revoke insert, update, delete, truncate, trigger, references on public.%I from public', t);
      -- The server writes these exclusively through the service role, which bypasses grants.
      execute format('grant all on public.%I to service_role', t);
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped. Restoring the write grant re-opens the second-control gap
-- (RLS would again be the only thing blocking anon writes to live game state).
--
--   grant insert, update, delete on public.ayo_sessions          to anon, authenticated;
--   grant insert, update, delete on public.checkers_sessions     to anon, authenticated;
--   grant insert, update, delete on public.checkers10_sessions   to anon, authenticated;
--   grant insert, update, delete on public.scrabble_player_state to anon, authenticated;
--   grant insert, update, delete on public.mahjong_player_state  to anon, authenticated;
-- ----------------------------------------------------------------------------
