-- Re-grant column-level SELECT on `tournaments` after the P0–P5 schema additions.
--
-- 20260803120000_lockdown_tournaments.sql replaced anon/authenticated's TABLE-level
-- SELECT with COLUMN-level grants (so `host_token` stays unreadable), and warned:
--
--   "⚠️ FUTURE SCHEMA CHANGES: ... Any NEW column must also be granted (re-running
--    this block does that) or client reads of it will error."
--
-- Six columns were added after that lockdown without re-running it:
--   game_queue (20260914)  custom_trivia_pack (20260915)  branding (20260916)
--   scheduled_at (20260917)  pending_host_player_id (20260918)
--   push_sent_t15_at / push_sent_t0_at (20260919)
--
-- Four of them are in TOURNAMENT_PUBLIC_SELECT in /api/tournaments/[code], which
-- reads through the ANON key — so without this migration that GET fails with
-- 42501 (permission denied for column) and the tournament page, the projector
-- screen, and every client that polls them break outright.
--
-- Fails closed by design: the symptom is a read error, never a token leak.

-- ---------------------------------------------------------------------------
-- Columns deliberately withheld from anon/authenticated
-- ---------------------------------------------------------------------------
--   host_token          — the host credential (original reason for the lockdown).
--   custom_trivia_pack  — the shared question pack for planned Trivia rounds.
--                         20260915 already states it must never reach a client:
--                         "leaking a CSV of pre-set answers to any caller with a
--                         tournament code would spoil every trivia round."
--                         Every read of it is service-role (the GET route returns
--                         only its LENGTH), so withholding it here turns that
--                         comment into an enforced guarantee instead of a
--                         convention the next `select('*')` could quietly break.
--
-- Everything else is granted, including the push_sent_* bookkeeping columns —
-- they're harmless to read and enumerating them keeps this block a straight
-- "re-run after any schema change" recipe.
do $$
declare
  tournament_cols text;
  role_name text;
begin
  select string_agg(quote_ident(column_name), ', ')
    into tournament_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'tournaments'
     and column_name not in ('host_token', 'custom_trivia_pack');

  foreach role_name in array array['anon', 'authenticated'] loop
    execute format('revoke select on public.tournaments from %I', role_name);
    execute format('grant select (%s) on public.tournaments to %I', tournament_cols, role_name);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   -- Restore the 20260803120000 grant set (host_token withheld, pack readable):
--   do $$
--   declare
--     tournament_cols text;
--     role_name text;
--   begin
--     select string_agg(quote_ident(column_name), ', ')
--       into tournament_cols
--       from information_schema.columns
--      where table_schema = 'public' and table_name = 'tournaments'
--        and column_name <> 'host_token';
--     foreach role_name in array array['anon', 'authenticated'] loop
--       execute format('revoke select on public.tournaments from %I', role_name);
--       execute format('grant select (%s) on public.tournaments to %I', tournament_cols, role_name);
--     end loop;
--   end $$;
-- ----------------------------------------------------------------------------
