-- Security audit H3 — the `avatars` bucket accepted anonymous uploads.
--
-- 0002_player_questions_and_avatars.sql created `public_avatars` as
-- `for all to anon` — read AND write — and 20260726130000_blog_images_bucket.sql
-- documents the reason: "the `avatars` bucket ... lets anon write, because players
-- upload their own photos directly".
--
-- That comment is now stale. `/api/photos` (the only avatar upload path) uploads with
-- the SERVICE ROLE after authorising the caller with `assertPlayer`, and additionally
-- enforces a 2MB cap, an allow-list of image MIME types and a magic-byte check. Nothing
-- in the codebase uploads to this bucket with the anon key.
--
-- Meanwhile the open policy was live: verified against the dev project that an anonymous
-- caller could both list the bucket and upload an arbitrary file to it (the test object was
-- removed afterwards). A public bucket that accepts anonymous writes is free file hosting
-- on your own domain — the standard abuse is malware and illegal content served from a
-- URL that looks like yours.
--
-- Fix: keep public READ (avatars render in-game from public URLs) and drop anonymous
-- write, matching the shape the `blog` bucket already uses correctly.

drop policy if exists "public_avatars" on storage.objects;

create policy "public_avatars_read"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'avatars');

-- No insert/update/delete policy, deliberately: uploads and cleanup run through
-- /api/photos with the service role, which bypasses RLS.

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   drop policy if exists "public_avatars_read" on storage.objects;
--   create policy "public_avatars" on storage.objects for all to anon
--     using (bucket_id = 'avatars') with check (bucket_id = 'avatars');
-- ----------------------------------------------------------------------------
