-- Stop anon from reading unpublished / future-dated blog posts via direct PostgREST.
--
-- blog_posts had `for select to anon, authenticated using (true)`, so anyone could
-- `supabase.from('blog_posts').select('*')` and read drafts and future-dated posts,
-- bypassing the app's published/not-future filter. The app itself reads blog posts ONLY
-- through the service-role client (src/lib/blog-server.ts, which filters in code, and the
-- admin routes) — nothing in the app relies on anon SELECT — so tightening the public
-- policy to published-and-live changes no app behavior while closing the leak.

do $$
begin
  if to_regclass('public.blog_posts') is not null then
    execute 'alter table public.blog_posts enable row level security';
    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_posts' and policyname = 'public_blog_posts_select') then
      execute 'drop policy "public_blog_posts_select" on public.blog_posts';
    end if;
    execute $p$
      create policy "public_blog_posts_select" on public.blog_posts
        for select to anon, authenticated
        using (status = 'published' and published_at is not null and published_at <= now())
    $p$;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   drop policy "public_blog_posts_select" on public.blog_posts;
--   create policy "public_blog_posts_select" on public.blog_posts for select to anon, authenticated using (true);
-- ----------------------------------------------------------------------------
