-- Content Collections — themed groupings of Library datasets across game types.
--
-- A "collection" (e.g. "Church & youth", "Corporate icebreakers", "African trivia") is a
-- curated, admin-authored group of existing Library packs (question_packs). Each pack is still a
-- normal per-game-type dataset that folds into games.custom_questions at create time, so this
-- feature needs NO changes to any game engine or start route — a collection is purely a
-- taxonomy layer ABOVE the Library.
--
-- SECURITY: unlike puzzle_themes / platform_content (whose `entries` hold secret answers),
-- collection metadata and pack↔collection membership are PUBLIC marketing content shown on the
-- /collections browse pages and in the create-page filter. So this mirrors blog_posts: RLS on
-- with a permissive-but-scoped public SELECT policy; all writes are service-role only behind
-- assertAdminRequest. Pack QUESTIONS are never exposed here — they still come only from the
-- existing /api/library/[id] endpoint.
--
-- No GRANT block needed: brand-new tables inherit Supabase's default table-level SELECT for
-- anon/authenticated. (The column-level GRANT gotcha only applies to games/players, whose
-- table-level grants were revoked in 0122.)

-- ---------------------------------------------------------------------------
-- content_collections: the collection itself (metadata only).
-- ---------------------------------------------------------------------------
create table if not exists content_collections (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,            -- URL key, e.g. 'church' -> /collections/church
  name text not null,                   -- display name, e.g. 'Church & youth group games'
  description text,                     -- shown on the browse page + create filter
  audience text,                        -- short label, e.g. 'Church & youth'
  icon text,                            -- emoji or icon slug for cards
  is_active boolean not null default true,
  sort_order integer not null default 0,
  builtin_key text unique,              -- idempotency guard for import-builtins seeding (NULL for hand-made)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_content_collections_active
  on content_collections (is_active, sort_order, created_at);

alter table content_collections enable row level security;
drop policy if exists "public_content_collections_select" on content_collections;
create policy "public_content_collections_select" on content_collections
  for select to anon, authenticated
  using (is_active = true);

-- ---------------------------------------------------------------------------
-- question_pack_collections: M2M membership. A dataset can live in several collections
-- (e.g. "General Knowledge" trivia in both a "General" and a "Family-friendly" collection).
-- ---------------------------------------------------------------------------
create table if not exists question_pack_collections (
  pack_id uuid not null references question_packs(id) on delete cascade,
  collection_id uuid not null references content_collections(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (pack_id, collection_id)
);

create index if not exists idx_qpc_collection on question_pack_collections (collection_id, sort_order);
create index if not exists idx_qpc_pack on question_pack_collections (pack_id);

alter table question_pack_collections enable row level security;
-- Membership is public (it's what the browse page renders). It reveals only which APPROVED pack
-- belongs to which ACTIVE collection; questions are never exposed through this table. Scope the
-- policy so rows for hidden collections aren't leaked.
drop policy if exists "public_question_pack_collections_select" on question_pack_collections;
create policy "public_question_pack_collections_select" on question_pack_collections
  for select to anon, authenticated
  using (
    exists (
      select 1 from content_collections c
      where c.id = question_pack_collections.collection_id and c.is_active = true
    )
  );

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   drop table if exists question_pack_collections;
--   drop table if exists content_collections;
-- ----------------------------------------------------------------------------
