-- Public profile username — the unique, claimable slug behind /u/<username>.
--
-- Batch 1 follow-on to the trophies feature: a shareable public trophy profile. `profiles.handle`
-- stays what it has always been — a NON-UNIQUE display name (two players called Naza is a normal
-- Tuesday). This adds a SEPARATE, unique `username` that a player deliberately claims when they
-- want a public link. Null until claimed: a profile with no username has no public page, which is
-- also the opt-in — you are not discoverable until you choose a handle for the URL.
--
-- SECURITY POSTURE (unchanged from 20260804000000, and see audit finding C2 in
-- docs/security-audit-2026-08.md): this migration creates NO view and grants the public roles
-- NOTHING new. The `public_profiles` view is deliberately left alone — broadening it is exactly
-- the class of change that let an anonymous console set another account's trophy_level to 999.
-- Every public read of a username-keyed profile is served by an API route holding the service
-- role, which is also what lets win-rate come from the service-role-only `player_stats` table.

alter table profiles add column if not exists username text;

-- Case-insensitive uniqueness, and only across CLAIMED usernames — many null rows must coexist.
-- The API stores a canonical lowercase value, so lower() here is belt-and-braces.
create unique index if not exists profiles_username_lower_key
  on profiles (lower(username))
  where username is not null;

-- Format guard mirrored in src/lib/profile/username.ts. Canonical form is lowercase, so the class
-- is [a-z0-9_]; the API lowercases before writing, and this refuses anything that slipped past it.
-- Reserved-word rejection lives in the API (it needs the route table), not here.
alter table profiles drop constraint if exists profiles_username_format;
alter table profiles add constraint profiles_username_format
  check (username is null or username ~ '^[a-z0-9_]{3,20}$');

-- No GRANT: `username` is read only through service-role API routes, never by an anon/authenticated
-- client directly (the same reason player_stats and the catalog are service-role-only). The owner
-- can still read their own row via the existing `profiles_select_own` policy.

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   alter table profiles drop constraint if exists profiles_username_format;
--   drop index if exists profiles_username_lower_key;
--   alter table profiles drop column if exists username;
-- ----------------------------------------------------------------------------
