-- Make progression counters atomic.
--
-- The award pass incremented in TypeScript: SELECT the row, add the delta, write the absolute
-- result. `awarded_sessions` serializes one (profile, session) pair, so it stops the SAME game
-- being awarded twice — but it does nothing for two DIFFERENT games finishing at once. Both
-- passes write the same `__global__` row, both read the same starting value, and the second
-- write silently discards the first player's game. A player in two rooms at once is ordinary
-- in a party app, and every counter downstream (trophies, levels, streak trophies) inherits
-- the loss with no error anywhere.
--
-- The fix is to do the arithmetic in Postgres, where `on conflict do update` reads the current
-- row under the write's own lock.

-- ---------------------------------------------------------------------------
-- bump_player_stats — additive upsert of one scope's counters.
-- ---------------------------------------------------------------------------
create or replace function bump_player_stats(
  p_profile_id uuid,
  p_game_type  text,
  p_played     integer,
  p_won        integer,
  p_counters   jsonb
) returns void
language plpgsql
-- SECURITY DEFINER so the award pass can write a table the API roles cannot reach at all.
-- Its REVOKEs are below, in this same file, and search_path is pinned so the body can't be
-- redirected by a caller-controlled path.
security definer
set search_path = public
as $$
begin
  insert into player_stats (profile_id, game_type, games_played, games_won, counters, updated_at)
  values (p_profile_id, p_game_type, greatest(p_played, 0), greatest(p_won, 0), coalesce(p_counters, '{}'::jsonb), now())
  on conflict (profile_id, game_type) do update
    set games_played = player_stats.games_played + greatest(excluded.games_played, 0),
        games_won    = player_stats.games_won + greatest(excluded.games_won, 0),
        -- Merge the jsonb bag key-by-key, summing shared keys. A plain `||` would REPLACE a
        -- key's value rather than add to it, which would reset late_night_games to 1 every time
        -- instead of counting.
        counters     = (
          select coalesce(jsonb_object_agg(key, total), '{}'::jsonb)
          from (
            select key, sum(value)::numeric as total
            from (
              select key, (value #>> '{}')::numeric as value from jsonb_each(player_stats.counters)
              union all
              select key, (value #>> '{}')::numeric as value from jsonb_each(excluded.counters)
            ) pairs
            group by key
          ) merged
        ),
        updated_at = now();
end;
$$;

revoke all on function bump_player_stats(uuid, text, integer, integer, jsonb) from public, anon, authenticated;
grant execute on function bump_player_stats(uuid, text, integer, integer, jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- recompute_profile_points — derive the cached totals rather than incrementing them.
-- ---------------------------------------------------------------------------
-- `profiles.trophy_points` had the same read-add-write race. It is DERIVED data — the sum of
-- what the player holds — so it is recomputed from `player_trophies` instead of accumulated.
-- Derivation is race-free by construction: two concurrent passes both arrive at the same total,
-- and it self-heals if a previous write was ever lost.
create or replace function recompute_profile_points(p_profile_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  total integer;
begin
  select coalesce(sum(t.points), 0)
    into total
    from player_trophies pt
    join trophies t on t.id = pt.trophy_id
   where pt.profile_id = p_profile_id;

  -- Level thresholds mirror LEVEL_THRESHOLDS in src/lib/trophies/award.ts. Kept in both places
  -- deliberately: the UI needs it without a round-trip, and the DB needs it to stay consistent
  -- when points are recomputed here.
  update profiles
     set trophy_points = total,
         trophy_level = case
           when total >= 8000 then 10
           when total >= 5000 then 9
           when total >= 3200 then 8
           when total >= 2000 then 7
           when total >= 1200 then 6
           when total >= 700  then 5
           when total >= 350  then 4
           when total >= 150  then 3
           when total >= 50   then 2
           else 1
         end
   where id = p_profile_id;

  return total;
end;
$$;

revoke all on function recompute_profile_points(uuid) from public, anon, authenticated;
grant execute on function recompute_profile_points(uuid) to service_role;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   drop function if exists bump_player_stats(uuid, text, integer, integer, jsonb);
--   drop function if exists recompute_profile_points(uuid);
--
-- The award pass would have to go back to reading and writing in application code, which is
-- the race this migration exists to remove.
-- ----------------------------------------------------------------------------
