-- Remove anon write/delete on the public `avatars` storage bucket.
--
-- The `public_avatars` policy was `for all to anon using(bucket_id='avatars')` with no
-- path/owner scoping — so any anon could overwrite or DELETE every object in the bucket,
-- or upload arbitrary files to a public CDN path. All legitimate avatar writes go through
-- service-role routes (src/app/api/photos/route.ts uploads/removes via supabaseAdmin), and
-- reads are served from the public bucket over the CDN (no SELECT policy required). So anon
-- needs, at most, read — never write/delete.
--
-- Replace the FOR ALL policy with a SELECT-only policy scoped to the bucket. The service
-- role bypasses RLS, so uploads/removals keep working.

drop policy if exists "public_avatars" on storage.objects;

create policy "public_avatars_read"
  on storage.objects for select to anon
  using (bucket_id = 'avatars');

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file.
--   drop policy if exists "public_avatars_read" on storage.objects;
--   create policy "public_avatars" on storage.objects for all to anon
--     using (bucket_id = 'avatars') with check (bucket_id = 'avatars');
-- ----------------------------------------------------------------------------
