-- Mark code-authored trophies as SYSTEM.
--
-- Two kinds of trophy now exist and they are not interchangeable:
--
--   ADMIN trophies are written in /admin/trophies out of the generic counter vocabulary
--   ("win 25 games"). They are data, and editing one is a normal product decision.
--
--   SYSTEM trophies are authored in code against a specific game's own measurements
--   ("answer 10 Trivia questions in a row"). Their rule is only meaningful alongside the facts
--   builder that emits those counters, so editing the row without changing the builder produces
--   a trophy that reads as zero forever — silently unearnable, indistinguishable from a typo.
--
-- Both must live in this table: `player_trophies.trophy_id` references it, so a trophy that is
-- not a row here cannot be awarded at all. The flag is what lets the admin UI show the true full
-- catalog while making clear which half is safe to edit.
--
-- Deliberately NOT a check constraint or a trigger. Enforcement belongs in the API, where it can
-- return a sentence explaining why, rather than in the database, where it would surface as a
-- constraint violation nobody can act on.

alter table trophies
  add column if not exists is_system boolean not null default false;

-- Existing rows were all seeded from the generic template catalog, which admin may legitimately
-- edit — so the default of false is already correct for every row present. No backfill.

comment on column trophies.is_system is
  'Code-authored trophy tied to a game-specific facts builder. Read-only in admin; may be retired but not edited.';

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   alter table trophies drop column if exists is_system;
--
-- Dropping it makes system trophies indistinguishable from admin ones, so the UI would offer
-- edits that silently break their rules. Only do this alongside removing the system catalog.
-- ----------------------------------------------------------------------------
