-- Per-game trophy accumulator for Whot (mirrors 20260811000000_crazy_eights_round_stats.sql).
--
-- WHY A COLUMN AND NOT A DERIVATION. Whot is a POSITION game: the session holds only the top card
-- and the piles, each hand holds only what a player is holding RIGHT NOW, and a finished hand is
-- empty. Facts like "played three Pick Twos", "went to market five times", "played four cards of
-- one shape in a row" or "won on a WHOT" do not survive to the end. So the engine counts them as
-- they happen — inside the atomic hand write it already does once it wins the turn's session CAS
-- (see foldWhotPlayStats / foldWhotDrawStats / foldWhotChooseStats in src/lib/whot.ts) — and stashes
-- them on this column. `src/lib/trophies/game-facts/whot.ts` reads the bag back at finish.
--
-- GRANTS. `whot_player_hands` (0064_whot.sql) has TABLE-level SELECT grants to anon/authenticated,
-- which auto-extend to a new column, so no explicit `grant select (stats)` is needed here — the same
-- reasoning as the Crazy Eights accumulator. (If that table ever migrates to column-level grants,
-- add `grant select (stats) on whot_player_hands to anon, authenticated;`.)
--
-- RESET. There is no explicit per-game reset: the accumulator lives on whot_player_hands, which is a
-- fresh row per (game_id, player_id), so each new game starts from the '{}' default. Play-again
-- clears the table entirely (see clearSessionTables in initializeWhotGame / clearWhotSession).

alter table whot_player_hands
  add column if not exists stats jsonb not null default '{}'::jsonb;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   alter table whot_player_hands drop column if exists stats;
--
-- Dropping it retires the Whot per-game trophies to "never earned" (the facts builder reads an
-- absent bag as all-zero), which is the state before this migration.
-- ----------------------------------------------------------------------------
