-- Snake & Ladder per-game trophy accumulator.
--
-- Same pattern as Ludo (20260811010000): the game only persists the LAST roll
-- (last_roll, last_from, last_to, last_event), not a move history, so a finish-time
-- facts builder has nothing to derive ladder/snake/six counts from. This column is
-- that trace: a per-game scratch counter blob the engine bumps IN PLAY, folded into
-- lifetime trophy counters at finish by src/lib/trophies/game-facts/snake-and-ladder.ts.
--
-- Shape (all optional, absent == 0): rolls, sixes_rolled, consecutive_sixes_max,
-- ladders_taken, snakes_hit, overshoots, busts, longest_ladder (jump distance),
-- reached_50 (0/1).

alter table snake_ladder_player_state
  add column if not exists game_counters jsonb not null default '{}'::jsonb;

grant select (game_counters) on snake_ladder_player_state to anon, authenticated;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   revoke select (game_counters) on snake_ladder_player_state from anon, authenticated;
--   alter table snake_ladder_player_state drop column if exists game_counters;
-- ----------------------------------------------------------------------------
