-- Durable per-round trophy facts.
--
-- THE PROBLEM THIS EXISTS TO FIX. Trophy facts were derived when the CLIENT posted attribution,
-- which happens after the finished screen mounts. But "play again" clears the game's session
-- tables and Chess's rematch blanks `chess_sessions.pgn` — so a host who replays quickly
-- destroys the evidence before any of it is read. This is not theoretical: there is already a
-- finished chess game in the production database with an empty PGN.
--
-- So the facts are now derived at FINISH, from `markGameFinished`, and written here. Attribution
-- reads this table instead of live session state, and can therefore arrive whenever it likes.
--
-- KEYED BY ROUND, NOT BY ROOM. "Play again" reuses the same `games` row, so one code covers every
-- round a room plays — the same trap that made `awarded_sessions` award only the first round.
-- `finished_at` is what separates them, and it is the same discriminator the award claim uses.
--
-- NOTHING MAY DELETE FROM THIS TABLE ON REPLAY. It is the durable copy of what the session rows
-- said before they were cleared; wiring it into a `clear*SessionData` helper would reintroduce
-- the exact bug it exists to fix. If these rows ever need pruning, prune on age.

create table if not exists round_facts (
  game_id     text not null,
  player_id   uuid not null references players(id) on delete cascade,
  finished_at timestamptz not null,
  -- Flat { counter_key: integer }. Deliberately not typed further: the vocabulary lives in
  -- src/lib/trophies/counters.ts and is enforced there, where the error can be explained.
  facts       jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  primary key (game_id, player_id, finished_at)
);

-- The award pass looks up one player's row for one round; attribution is the only reader.
create index if not exists idx_round_facts_lookup on round_facts (game_id, player_id);

-- ---------------------------------------------------------------------------
-- Lock it down. Same two controls as the other trophy tables: RLS with no
-- policies (deny-all for everything except the service role, which bypasses RLS
-- by design) AND explicit revokes, in this same file.
-- ---------------------------------------------------------------------------
alter table round_facts enable row level security;

revoke all on table round_facts from public;
revoke all on table round_facts from anon;
revoke all on table round_facts from authenticated;
grant all on table round_facts to service_role;

comment on table round_facts is
  'Per-round, per-player trophy facts derived at finish. Read by the award pass. Never deleted on play-again — that is the point.';

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   drop table if exists round_facts;
--
-- Dropping it returns trophy derivation to attribution time, where play-again can destroy the
-- evidence first — so only do this alongside reverting the finish-time hook.
-- ----------------------------------------------------------------------------
