-- Describe It — public per-word counter. ADDITIVE ONLY; no grant is taken away here.
--
-- This is deliberately a separate migration from 20260807130000 (which revokes the secret
-- columns). Review on PR #866 flagged that doing both in one file creates a deploy-skew trap
-- with no safe ordering: the single migration simultaneously CREATES the column new clients
-- need and REMOVES the columns old clients read, so whichever side you deploy first, the other
-- side breaks. Splitting them gives the rollout a window (see ROLLOUT ORDER in 20260807130000).
--
-- Applying this file is safe against EVERY client version, old or new: adding a column cannot
-- break an explicit PostgREST select, and no existing privilege changes.
--
-- WHAT IT IS FOR: `describe_it_sessions.used_words` is a shadow copy of the secret word (every
-- write that sets `current_word` appends that word, so `used_words[last]` IS the current word),
-- and 20260807130000 revokes it. The clients' one legitimate use of that array was its LENGTH:
-- the word rotates on a correct guess and on a skip *without* `turn_index` changing, so the
-- describer needs a public value that ticks once per word to know when to refetch. This is that
-- counter, and a count reveals nothing about the words.

do $$
begin
  -- ABORT rather than skip when the table is absent.
  --
  -- Skipping returns successfully, so this migration is recorded as applied — and if
  -- `describe_it_sessions` is created afterwards, `word_seq` and its grant are never installed.
  -- Nothing would fail loudly: `readDescribeItSession()` retries without `word_seq` on 42703, so
  -- the database stays permanently on the slower compatibility path while looking healthy.
  --
  -- The table is created by 0092_describe_it.sql, which sorts far earlier, so in any correct
  -- apply order it exists. Its absence here means the chain is genuinely broken, and that should
  -- stop the deploy rather than be papered over.
  if not exists (
    select 1 from information_schema.tables
     where table_schema = 'public' and table_name = 'describe_it_sessions'
  ) then
    raise exception 'describe_it_sessions is absent — 0092_describe_it.sql must run before this migration';
  end if;

  execute 'alter table public.describe_it_sessions
             add column if not exists word_seq integer
             generated always as (cardinality(used_words)) stored';

  -- Explicit, even though anon/authenticated still hold table-wide SELECT at this point: after
  -- 20260807130000 the grant is COLUMN-level, and a table-level grant does not cover columns
  -- added later. Granting here means this file is idempotent in either order.
  execute 'grant select (word_seq) on public.describe_it_sessions to anon, authenticated';
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped. Only safe once no client selects `word_seq`.
--
--   alter table public.describe_it_sessions drop column if exists word_seq;
-- ----------------------------------------------------------------------------
