-- Checkers / Draughts per-game trophy accumulator.
--
-- All three variants (American 8x8 `checkers`, and the 10x10 `checkers_international`
-- and `checkers_nigeria`, which share `checkers10_sessions.variant`) keep a POSITION,
-- not a record: `board` is only the current placement of the pieces. A crowning, a
-- multi-jump chain, an enemy king taken, the worst deficit you clawed back from — none
-- of it survives the hop once `board` is rewritten. Unlike Chess (replay the PGN) there
-- is nothing to derive these from after the fact, so this is that trace.
--
-- WHY PAIRED COLUMNS, NOT ONE PER PLAYER. Checkers stores its whole game on ONE session
-- row with `red_*` / `black_*` columns (`red_time_ms`, `black_time_ms`, …); there is no
-- per-player table to hang a `game_counters` blob on the way Ludo does. So the accumulator
-- mirrors that layout exactly: `red_stats` for the Red seat, `black_stats` for the Black
-- seat. The facts builder (src/lib/trophies/game-facts/checkers.ts) maps red_stats ->
-- player_red_id and black_stats -> player_black_id at finish.
--
-- These are per-GAME state: `initialize*Game` overwrites the whole row on a rematch (and
-- resets the board), so the blobs reset with it. The engines write them INSIDE the same
-- optimistic-concurrency (CAS on updated_at) window that guards every board write (see
-- persistSession in src/lib/checkers.ts and src/lib/draughts10.ts) — only the request that
-- wins the CAS ever commits, so a hop is never double-counted. Nothing about move, capture
-- or win legality changed; these writes are purely additive.
--
-- Shape (all optional, absent == 0): captures, kings_made, enemy_kings_captured,
-- best_chain (longest capture chain this game), chain_cur (hops in the chain in progress),
-- peak_kings (most kings held at once), max_deficit (worst piece deficit faced), turns
-- (this seat's completed turns), back_streak / back_streak_max (consecutive turns holding
-- the home back rank), made_capture_last_turn (0/1, for the Trade recapture check),
-- trades, reached_endgame (0/1), and flying_king_max (longest king hop — 10x10 only).

alter table checkers_sessions
  add column if not exists red_stats jsonb not null default '{}'::jsonb,
  add column if not exists black_stats jsonb not null default '{}'::jsonb;

alter table checkers10_sessions
  add column if not exists red_stats jsonb not null default '{}'::jsonb,
  add column if not exists black_stats jsonb not null default '{}'::jsonb;

-- Column-level SELECT, mirroring 20260811010000_ludo_round_stats.sql. These tables
-- currently hold a TABLE-level SELECT grant for anon/authenticated (they predate the
-- column-level lockdown that only reworked `games`/`players` in 0122), so this grant is
-- belt-and-braces: harmless where a table grant already covers it, and the thing that
-- keeps client realtime subscriptions (which select every column) from a 42501 if that
-- table grant is ever tightened to column level. Server writes/reads use the service role
-- and bypass grants entirely.
grant select (red_stats, black_stats) on checkers_sessions to anon, authenticated;
grant select (red_stats, black_stats) on checkers10_sessions to anon, authenticated;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   revoke select (red_stats, black_stats) on checkers_sessions from anon, authenticated;
--   revoke select (red_stats, black_stats) on checkers10_sessions from anon, authenticated;
--   alter table checkers_sessions   drop column if exists red_stats, drop column if exists black_stats;
--   alter table checkers10_sessions drop column if exists red_stats, drop column if exists black_stats;
-- ----------------------------------------------------------------------------
