-- Security audit H2 — the Codewords key card was public.
--
-- 0118_rls_lockdown_codewords.sql correctly removed the write policy but left
-- `create policy "codewords_boards_read" on codewords_boards for select using (true)`.
-- Row-level access grants EVERY column in the row, and this row's entire purpose is a
-- secret: `key` is the red/blue/neutral/assassin assignment for all 25 words.
--
-- Verified live: with the publishable anon key, `select * from codewords_boards` returned
-- a real game's `key`. The clients fetched the whole row and only *rendered* it differently
-- for operatives — a client-side secret, i.e. no secret. Any player could read their own
-- network response, win every game, and avoid the assassin.
--
-- Same shape as `games.host_token` in 0122, so the same fix: revoke the public roles'
-- table-wide SELECT and re-grant every column except `key`. The service role bypasses column
-- grants, so /api/codewords/board (which decides who is entitled to the key) keeps working,
-- as do the nine codewords write routes, which all already use it.
--
-- Realtime: anon `postgres_changes` payloads exclude columns the role cannot select, so `key`
-- stops arriving over realtime too. The two board consumers therefore preserve the key they
-- already hold when a key-less payload lands, and re-fetch through the route when the board
-- itself is replaced. See CodewordsHostView / CodewordsPlayerView.
--
-- ⚠️ FUTURE SCHEMA CHANGES: anon/authenticated now hold COLUMN-level (not table-level) SELECT
-- on `codewords_boards`. A NEW column must also be granted (re-running this block does that),
-- or client reads of it will error. Fails closed — a read error, never a key leak.

do $$
declare
  board_cols text;
  role_name text;
begin
  select string_agg(quote_ident(column_name), ', ')
    into board_cols
    from information_schema.columns
   where table_schema = 'public' and table_name = 'codewords_boards' and column_name <> 'key';

  foreach role_name in array array['anon', 'authenticated'] loop
    execute format('revoke select on public.codewords_boards from %I', role_name);
    execute format('grant select (%s) on public.codewords_boards to %I', board_cols, role_name);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- ROLLBACK (drafted). Apply as a NEW forward migration; do NOT edit this file
-- after it has shipped.
--
--   grant select on public.codewords_boards to anon, authenticated;
-- ----------------------------------------------------------------------------
